### ISSUE TITLE
Import EML folder only imports some of the emails

### ISSUE THREAD

**Issue by TomShab** [thundernest/import-export-tools-ng#149] opened 2020-09-15 21:17 UTC
Hello Christopher,

My Windows Live Mail died last night so I decided to migrate to Thunderbird 
I installed the last version & added ImportExportTools last version (from several days ago I think since Thunderbird doesn't let you add older versions)

I am trying to import tens of thousands of EML files & I am using this tool. For some reason when I try to import a folder of EML files it only imports some of them. I checked it out & it's not because the other files are corrupted - they can imported one at a time. I looked at the config options & nothing. 
I tried it on several folders of EML with the same result. It seem that when it import in bulk it skips specific EML files - tried to see if it's specific files - and yes it is, but I don't know why, and what so special about them that it only can be migrated one by one

I appreciate your help

Best Regards,
T

**Comment by cleidigh** [comment] 2020-09-15 21:47
@TomShab 
thanks for making the post,  this is really the only practical way to work on the problems's.
couple of things up front:
- as you are new to Thunderbird I will do my best not to assume familiarity
- I have to do everything by voice being disabled, I try to keep everything short and I frequently just not correct things as it's a lot of work ... Please ignore the grammar and punctuation errors!

Unfortunately there are way too many scenarios for problems with e-mail.  there are plenty of users who have imported from Windows live Mail , almost all without problems.
thanks to your prior experiments we can pretty much excludes the most difficult issues concerning e-mail headers.    that leaves us with a couple typical issues:s 
-  filename length  issues 
-  Windows open file limits ( can be exceeded with many folders)

Both of the above issues should produce some errors in the console these are part of several things I am currently working on for the new release

so the first thing we should just check out the log:
go to the following menu option:
Tools/DeveloperTools/Error Console
this opens a new window, try the smallest import you know causes issues and select all of the debug output Copy, then you can paste easier for us to look at.
createsubfolder and addmessage are two things to look for.
I also have a new beta which addresses some of the issues are still found in
4.1
EML import is pretty solid and fixing some of the things mentioned above.
if you want to try you'll have to follow several manual steps, you cannot get it from the website yet.
also if you can clarify the following
OS, TB extension versions just to be clear
approximate number of folders you are trying to import
Christopher

**Comment by cleidigh** [comment] 2020-09-15 21:59
@TomShab 
Example screenshot
you get the context menu with Right Click
![image](https://user-images.githubusercontent.com/25272315/93269543-2dd30c00-f77d-11ea-83c1-fac576217a96.png)

**Comment by TomShab** [comment] 2020-09-15 22:14
Thanks,

I am using: 

Windows 10 Home Version 10.0.19041
Thunderbird 78.2.2 (32-bit)
ImportExport Version  10.0.0.-b12
                  
I attached the error screen shot

![thunderbird_error2](https://user-images.githubusercontent.com/71352617/93270387-b2438000-f7b9-11ea-8793-97772d19f58a.jpg)



Regards,
  T.

**Comment by cleidigh** [comment] 2020-09-15 23:08
Okay important to know you are using 78
you just have to realize I am still not released for that yet.
I have multiple beta users that have done imports successfully so definitely important to figure out what's going on in your situation.  the problem with your screen capture is that it only shows part of the log
to get the whole log still the right click, SelectAll, Copy (have to use control C) and you can paste here
to get the best output, start everything, open the console window, click the trash to get a blank screen
go back to Thunderbird do the import operation, Go back to the debug console and capture that output
Christopher

**Comment by cleidigh** [comment] 2020-09-15 23:56
@TomShab 
if you works for you, I can also do a Zoom chat to try and solve this real-time
I'm not sure where you're located, I am in Rhode Island on the East Coast
most days I can do call 3EDT-9:30
we might be able to find the issues faster this way

**Comment by TomShab** [comment] 2020-09-16 12:00
I have only one add ons - ImportExport

I did what you have asked and here is the screen shot:

![thunderbird_error3](https://user-images.githubusercontent.com/71352617/93334295-63373280-f82d-11ea-9746-c65751acf5ee.jpg)

**Comment by cleidigh** [comment] 2020-09-16 17:44
@TomShab 
oh well, that doesn't give us anything to go on.
this means were going to have to do more experiments
For right now this is the only outstanding potentially important bug and therefore important to identify.
can you give me an idea how you would like to proceed ?
Christopher

**Comment by TomShab** [comment] 2020-09-16 20:25
I played with it a little & when I change the order I pick the EML's I get a different results. That suggests that the problem isn't with the files

**Comment by TomShab** [comment] 2020-09-16 21:04
I find a way to do it. I am using IMAPSize to convert it to mbox file & than use ImportExport on the mbox file. Works!

**Comment by cleidigh** [comment] 2020-09-16 21:19
That sounds good
unfortunately it doesn't tell us why the original files cause a problem
it sounds like you probably do not want to waste time analyzing?

**Comment by TomShab** [comment] 2020-09-16 21:36
I want to help to solve this problem. Do you have any suggestion?

**Comment by cleidigh** [comment] 2020-09-16 22:02
I appreciate that!
basically we have two ways back and forth here or doing a Zoom with screen share
I am still hopeful we can figure out a way to get to debug output

**Comment by cleidigh** [comment] 2020-09-16 22:02
in either case we want to find the minimum of set of e-mails that causes the problem
we can use a separate profile to make sure we don't mess anything up

**Comment by cleidigh** [comment] 2020-09-16 22:11
I somehow missed your comment about two EMLs 
I understood that on retesting  specific emails were no longer obvious?

**Comment by TomShab** [comment] 2020-09-16 22:17
I can't Zoom because I barely speak

As I told you there are different results when I change the order of the eml's I import 

I can find some eml files to send you if you are interested to check. I can do it tomorrow (it's past midnight at my timezone)

**Comment by cleidigh** [comment] 2020-09-16 22:25
@TomShab 
I totally understand, I can speak but I can't Move as I have ALS...
I will try and write some notes for experiments 
I don't think there's any point in you sending me individual e-mails as you said the breakpoints not consistent
I have to get some debug for us

**Comment by cleidigh** [comment] 2020-09-17 01:19
information questions
- total number of e-mails and folders
- folder structure you can create with the command
dir /A:D > directories.txt
 you can post a here
I also want to reverify that the last log was open to Sure before you did the import
Christopher

**Comment by cleidigh** [comment] 2020-09-17 01:24
thought of a couple other questions
how did you know that some e-mails were not imported?
actually just at this moment I thought of a critical question:
your first post said that Live died, how did you get the export from that?
are you trying to import from the Windows Live message structure directly?

**Comment by TomShab** [comment] 2020-09-17 15:39
I'm sorry to hear that. Best wishes 

>>total number of e-mails and folders
>>folder structure you can create with the command

Will do it later 

>>how did you know that some e-mails were not imported?

I imported ~4200 email and got only ~2300. I mean you can see that in Thunderbird. I also looked for individuals emails & saw they weren't imported (tried collapse/uncollapse conversations, closing & opening TB). I tried it on several folders (with different number of emails) with the same results - not all email were imported. When I convert it to mbox & then import mbox it imports all the eml's

>>your first post said that Live died, how did you get the export from that?

Windows 10 was updated and then connection to email server didn't work anymore via WLM. I google it and saw it was a problem other people had, tried to fix it (with regedit, big mistake) the way they did & it made all my emails unavailable for reading, but the emls were still there so I copied them to my desktop & from there I continued (installing TB, ImportExport....)

I have to say that in some aspects TB is better than WLM

**Comment by cleidigh** [comment] 2020-09-17 19:21
@TomShab 
Thanks, obviously we both have some challenges, but we will work it out!

very important:  please correct me if I am wrong as this is new understanding:

[Because WL died and you tried to correct things based on some suggestions, WL essentially became inoperable, 
THEREFORE you did not do a typical export you are just able to access Windows live database/file folders]

If that is true, we have to figure out 'what exactly we have to work with.  my assumption is when you try to import 4200 messages (EML files?)  it hit an error ~2300  meaning that it did not drop e-mails here and there it just Fails part way through.

as I mentioned before the Windows file was previously an issue where one could see failures ~400 file operations
b13 should fix that issue which I worked on forever.  I don't understand it, but it sounds like something like that might still be happening, we just haven't seen the error messages yet.
I believe you are located somewhere in Europe given the six hour difference.  I have an odd schedule where I can basically be on online 3-11 EDT each day so you know when we could go back and forth easily

I will try and post something with more output and then once I understand your folder structure and contents we will figure out the best order of experiments.

I think you'll find far superior to Windows live, I have been using for years as well as for my wife's business.
I hope you don't get discouraged by this bump    the road!

**Comment by cleidigh** [comment] 2020-09-17 23:03
I have a version extra debug
just detach it from here and load into Thunderbird for the extension is Zip which is compatible with xpi
I am also attaching example output
[import-export-tools-ng-10.0.0-b14x1-tb.zip](https://github.com/thundernest/import-export-tools-ng/files/5242363/import-export-tools-ng-10.0.0-b14x1-tb.zip)

[doutput.txt](https://github.com/thundernest/import-export-tools-ng/files/5242365/doutput.txt)

**Comment by heliomoreno** [comment] 2020-09-18 18:43
> 
> 
> I have a version extra debug
> just detach it from here and load into Thunderbird for the extension is Zip which is compatible with xpi
> I am also attaching example output
> [import-export-tools-ng-10.0.0-b14x1-tb.zip](https://github.com/thundernest/import-export-tools-ng/files/5242363/import-export-tools-ng-10.0.0-b14x1-tb.zip)
> 
> [doutput.txt](https://github.com/heliomoreno/DevOpsLab-HelloWorld/blob/master/output.txt)

**Comment by TomShab** [comment] 2020-09-18 19:42
Sorry for the delay.

I don't get an error message. It just not imports all the eml's

I attached the log file & the directory structure (this is my basic trial - two eml's - the addon import only one) 

[log.txt](https://github.com/thundernest/import-export-tools-ng/files/5247805/log.txt)


[directories.txt](https://github.com/thundernest/import-export-tools-ng/files/5247767/directories.txt)

**Comment by heliomoreno** [comment] 2020-09-18 20:38
In my case, I exported the folder with 4000 eml and then on time and only imported 544 imported in another folder, of course.
Thunderbird 78 and 68 same error.
1st Windows 10 pro 64 - 8gb
2nd Windows 10 pro 32 - 2gb

**Comment by cleidigh** [comment] 2020-09-18 20:39
@TomShab 
no problem
only two? something very weird is going. is there anything special about these e-mails?
possibly send me  with personal stuff worked out?
I will also think about more output

**Comment by cleidigh** [comment] 2020-09-18 20:43
@heliomoreno 
okay that gives me some  potentially good info 544
is close to the Windows limit that should be fixed
More debug out  still needed
am I correct that all these messages are in one folder?

**Comment by TomShab** [comment] 2020-09-18 21:18
It's a trial folder. The two specific eml's I used for this trial were nested but I tried it with eml's that aren't related & I got the same result - less imported emails than selected

**Comment by cleidigh** [comment] 2020-09-18 21:22
are they something you could send me ?
something I have not seen

**Comment by cleidigh** [comment] 2020-09-18 21:25
@heliomoreno 
your log only  shows 5381 messages scanned (first phase before import) is this correct?
your post said 4000 messages was that only approximate ?

**Comment by heliomoreno** [comment] 2020-09-18 22:23
I'm in Brazil and I don't speak English so I'm using Google.
Not to be exact, 4001 were used in the tests. The export was carried out right after the import in a new folder, which was 420, so I exported from 420 to a new folder and with the hash of each file, I eliminated the remaining 3581, which did not matter.
As I got stuck, I used another import tool for EML.
But I really like this extension of the thunderbird. And that much help.

**Comment by cleidigh** [comment] 2020-09-18 23:35
@heliomoreno 
good to know, Rio? (one of my favorite cities!)
I will try to make English as clear as possible.
I have to use dictation as I am disabled.  you will see grammatical errors et cetera

b14x2 has more output  we are still missing the error
you should try and identify the simplest/smallest message import that causes a problem
consistently
then we will add more output if necessary
Tudo bem?

**Comment by heliomoreno** [comment] 2020-09-19 14:06
I'm from São Paulo, but I really like Rio de Janeiro, a folder import test with two emails was carried out and only one was imported, but if I have to import the other individually, I imported it into a local folder, so imap remote folder doesn't matter nothing.
I hope to have help now.

![Capturar](https://user-images.githubusercontent.com/40863312/93669066-9b29ba00-fa67-11ea-8ea7-5bcc6357abb6.PNG)
[outdir.txt](https://github.com/thundernest/import-export-tools-ng/files/5249972/outdir.txt)
[output_2.txt](https://github.com/thundernest/import-export-tools-ng/files/5249974/output_2.txt)

**Comment by cleidigh** [comment] 2020-09-19 19:43
@heliomoreno 
@TomShab 
I found just stupid mistake  in one prior fixes that caused every other message to be skipped.
that is why you both saw half of e-mails imported
I think this was a temporary problem, introduced independent of your issues.
so with x3 'should try normal imports
[import-export-tools-ng-10.0.0-b14x3-tb.zip](https://github.com/thundernest/import-export-tools-ng/files/5250512/import-export-tools-ng-10.0.0-b14x3-tb.zip)

**Comment by heliomoreno** [comment] 2020-09-20 00:24
Really with this x3 imported the 14 to local and remote imap folder. Then I will perform a test with a larger mass.

**Comment by TomShab** [comment] 2020-09-20 02:45
>> I found just stupid mistake in one prior fixes that caused every other message to be skipped.

OK, It's working now. Thanks!

**Comment by cleidigh** [comment] 2020-09-20 02:54
@TomShab 
so your large import worked?
excellent
@heliomoreno 
@TomShab 
if both of your imports are working Shall we close?
Christopher

**Comment by TomShab** [comment] 2020-09-20 14:05
Yes, large import works now

Thanks again for your help

**Comment by cleidigh** [comment] 2020-09-21 02:07
@heliomoreno 
@TomShab 
thanks again guys, have found a few more issues but getting very close

**Comment by stjenna** [comment] 2020-09-24 17:28
I am also having this problem. I thought it was because I was importing 40k+ emails, but even when I broke them down into smaller batches, not all of them imported.

OS, TB extension versions just to be clear: Mac 10.15.4, TB 68.12.0
Approximate number of folders you are trying to import: Originally 1, but I've since split it into smaller batches in separate folders, since I thought the number of messages might be the issue.

I was going to try importing again, but I was afraid of creating duplicate messages. It seems like the importing stops when it's about 80% complete on a folder. I recently tried importing a folder of 1414 messages and only 1153 imported.

Thank you for any help you can provide! 
<img width="894" alt="Screen Shot 2020-09-24 at 1 27 27 PM" src="https://user-images.githubusercontent.com/71843326/94178928-c34f5980-fe69-11ea-94c1-d80cea84c938.png">

**Comment by cleidigh** [comment] 2020-09-24 17:49
@stjenna 
thanks for the post, but now I am bummed out I was just cleaning for release!
first thing, which Beta  version are you using?  b15 is the latest posted last night
it has a fix for an image issue, this might possibly be your issue.
We want to try to determine if it is a specific e-mail or structural issue
There are a couple of things you can do for experimentation safety
one of the easiest is to create a separate profile for testing
importing to separate local folder is pretty safe well
40k messages is not a problem assuming no problems of content
Christopher

**Comment by stjenna** [comment] 2020-09-24 21:26
I downloaded importexporttools_ng-4.1.0-tb.xpi on Sep. 21. The emails were exported from Thunderbird.

Based on that info, should I still try importing to a local folder? Or is there something else I should try first?

Thanks for being so prompt with your response!

**Comment by cleidigh** [comment] 2020-09-24 22:09
yes you should use the local folder
however the real thing is to use
the new b15 as it takes care of quite a number of issues
I am online now you want to go through it
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.0/xpi/import-export-tools-ng-10.0.0-b15-tb.xpi
Christopher
I try always to be prompt, just before release it's extra important !

**Comment by cleidigh** [comment] 2020-09-28 01:54
@stjenna 
any luck?

**Comment by stjenna** [comment] 2020-09-28 22:04
I'm now using the latest version and importing locally and it's going so much faster! Thank you! However, the number of messages imported does not match what I have in my folders. Based on the folder records, I should have 11,937 messages, but only 11,934 show in the Thunderbird folder. Any suggestions?

**Comment by cleidigh** [comment] 2020-09-28 22:10
@stjenna 
any errors in the console?
could be a malformed message, there are so many ways to have problems
four testing you could try to import to another folder and see if you get the same results
if we identify particular e-mails, we may discover header issue or something
C

**Comment by stjenna** [comment] 2020-09-29 00:39
This is the only error message I see.

![error-message](https://user-images.githubusercontent.com/71843326/94499424-a947ab00-01ca-11eb-96a4-81d855d12f85.jpg)

**Comment by cleidigh** [comment] 2020-09-29 03:26
@stjenna 
thanks, that something to start with.
you stated you were importing around 11k messages
missing 4, correct?
I assume that the image above does not show subsequent
message DB lines after the err?
this is a new type of error I have not seen , 
if I throw several experiments at you can you help with debugging?
I ask because these types of issues typically take a bunch of back-and-forth
until I reproduce something on my side.

the first thing I spoke about before is to see if the errors are consistent
by doing  several imports
also based on the above, I presume you could identify the particular e-mail that includes
the jpg attachment.  trying to import that single message would possibly identify
if it is a message or process issue
I have also done Zoom sometimes to work with people directly
Christopher

**Comment by stjenna** [comment] 2020-09-29 03:32
Yes, 4 missing of the 11k. There was nothing below the error message I sent. Happy to help debug, although it may be over the next few days due to my workload. 

Based on the error message I sent, I cannot easily identify the problem file (search did not bring anything up).

I am available to Zoom tomorrow from 3PM to 5PM ET. I have more availability later in the week.

Thanks so much for your help!

**Comment by cleidigh** [comment] 2020-09-29 03:38
@stjenna 
Great!
you sound busy, but how about I try to add some more debug
then we will schedule a chat so we are more efficient
it sounds like you are on the East Coast? 3-5 works very well for me most days
so I will think about next steps, have to get this rocksolid!
appreciate the help...
Christopher

**Comment by cleidigh** [comment] 2020-09-29 05:23
@stjenna 
another clarification
based on the screenshot it looks like you were perhaps doing subset import?
based on the output as it appears that no more than 3600 messages were imported
because the 'message DB' are after every 400 messages imported
is that correct?

**Comment by stjenna** [comment] 2020-09-29 16:51
I was choosing all the messages in a single folder. Each folder has between 1000-6000 messages in it. I imported three separate folders then took a screenshot of the error log.

Should we set up a Zoom call for 3:30PM ET?

**Comment by cleidigh** [comment] 2020-09-29 17:24
@stjenna 
not today, I have a Thunderbird meeting
also to be efficient want to give you some more debug
I will try and post something for you

**Comment by cleidigh** [comment] 2020-09-29 18:32
@stjenna 
I think I could do a brief call at around 4:15
we could briefly discuss next steps as well as clarify where we are
I have to do everything by voice being disabled so talking is far easier to get through things
it's up to you 
@cleidigh

**Comment by cleidigh** [comment] 2020-09-29 19:36
@stjenna 
okay done with my meeting, just let me know if you want your short chat

**Comment by stjenna** [comment] 2020-09-29 20:30
Sure. Sorry for the delay. Please let me know how to get in touch.

**Comment by cleidigh** [comment] 2020-09-29 21:00
if it's okay
send me an e-mail and I will send you an invite

**Comment by stjenna** [comment] 2020-09-29 21:43
Sent! Please let me know if you did not get it.

**Comment by stjenna** [comment] 2020-09-29 22:26
[error log](https://github.com/thundernest/import-export-tools-ng/files/5302148/error.log)

**Comment by cleidigh** [comment] 2020-11-16 19:19
Fixed:
v10.0.2

**Closed by cleidigh** 2020-11-16 19:19 UTC
Labels: EML, import
