### ISSUE TITLE
Header/footer for PDF export doesn't respect preferences

### ISSUE THREAD

**Issue by Razzmatazzz** [thundernest/import-export-tools-ng#77] opened 2020-02-14 18:25 UTC
The current version uses default print settings for the header and footer when saving emails to PDF (printEngineWindowOverlay.js:25). This doesn't respect the header and footer settings a user has configured in the print settings of Thunderbird. Therefore, every exported PDF always has the subject in the top left header, the pages in the bottom left footer, and the date the PDF was created in the bottom right footer. Would it be possible to load the appropriate settings (headerStrleft, headerStrCenter, headerStrRight, footerStrLeft, footerStrCenter, footerStrRight) from preferences into the print settings for the PDF convert?

**Comment by cleidigh** [comment] 2020-02-15 01:16
@Razzmatazzz 
Thanks !
I see the code using global defaults.  I finally found how to get to preferences correctly.
I am wondering if people will be surprised by this change since the default output will no longer be the same .  Any opinion?
I will post this in the Beta I'm working on.
@cleidigh

**Comment by Razzmatazzz** [comment] 2020-02-15 01:27
Wow, thanks for the quick response! Yeah, people might be a bit confused at first, but I was confused by the way it currently behaves because I was changing the print header/footer settings but the PDFs kept coming out the same (default) way. Could be a transition period at first, but I think it'll be more intuitive in the long run. Awesome job on the plugin in general, too!

**Comment by cleidigh** [comment] 2020-02-15 21:15
@Razzmatazzz 
check out beta 12
https://github.com/thundernest/import-export-tools-ng/blob/import-tests/xpi/import-export-tools-ng-4.0.5-b12-tb.xpi
lots of debug junk, but also the printer fix.  I just tested changing to landscape with margins in different titles including changed headers and footers.
@cleidigh

**Comment by Razzmatazzz** [comment] 2020-02-16 15:16
@cleidigh 
Works great! Many thanks for the quick fix!

**Comment by cleidigh** [comment] 2020-02-17 01:44
@Razzmatazzz 
Great!
Reviews always welcome.
I am hoping but not sure if I can get out an update this week.
you will know I close this issue and post it.

**Comment by cleidigh** [comment] 2020-04-28 01:54
Added:
4.1.0

**Closed by cleidigh** 2020-04-28 01:54 UTC
Labels: PDF, bug, enhancement, export, verified

**Comment by cleidigh** [comment] 2020-05-12 18:59
@Razzmatazzz 
I assume you have already, the upgrade including this enhancement.
I was hoping to be able to possibly get some help from you as I have a couple of users down reporting problems with PDF output.  I have so far been unable to reproduce the issue with margins.
Would you mind joining the discussion in #106 ?
I'm trying to figure out difference between users that makes this happen.
Thanks
@cleidigh

**Comment by Steven684** [comment] 2022-05-01 22:05
Hi,
can it be, that this problem is un-solved, now printEngineWindowOverlay.js is in 'obsolete/'?

I am using version 11.1 (although helpfiles say 10.0.2), and all my print.print*.print_header* show either nothing (empty) or &T. But all my exported pdf's show both Title and Url in the header....
