### ISSUE TITLE
Export in pdf issue

### ISSUE THREAD

**Issue by andredimu** [thundernest/import-export-tools-ng#24] opened 2019-10-21 10:26 UTC
for inbox messages:
when Save selected messages > PDF format
in the output file, in the header not all recipients in to:... and Cc:... field are showed but only the first item.
For sent message, all recipients are showed only if the full header view is activated.

**Comment by andredimu** [comment] 2019-10-21 14:43
> for inbox messages:
> when Save selected messages > PDF format
> in the output file, in the header not all recipients in to:... and Cc:... field are showed but only the first item.
> For sent message, all recipients are showed only if the full header view is activated.

the problem occurs when the export of messages is made from the folders on the server (inbox, sent, ...).
If the export is made from local folders, all recipients are correctly listed in the pdf file

**Comment by cleidigh** [comment] 2019-10-22 03:10
@andredimu 
Thanks for the issue posting.
I believe I understand your two descriptions above.  I just did a test using Thunderbird 68.1.2 with ImportExportTools NG 4.0.4 under Windows 10 printing single e-mail with three recipients. The signal e-mail was on the inbox on the server.  Can you identify the versions you are using as well as any debug console output.  It will be very difficult to solve without being able to reproduce the error.

I believe the output looks good.  
![image](https://user-images.githubusercontent.com/25272315/67257047-e7373d80-f457-11e9-8f85-282d383015c1.png)

**Comment by andredimu** [comment] 2019-10-22 07:30
Dear Christopher,
I attached the preview of the message and the output pdf.
My version is 68.1.2 (32 bit)  with ImportExportTools NG 4.0.4 under
Windows 7 professional SP1.
How can I get the debug console output?
Thank you for tour help.

Andrea

[image: 201910220918.jpg]



Informazioni di base
Nome Thunderbird
Versione 68.1.2
ID build 20191008153335
Canale di aggiornamento release
User agent Mozilla/5.0 (Windows NT 6.1; WOW64; rv:68.0) Gecko/20100101
Thunderbird/68.1.2
SO Windows_NT 6.1
Processo launcher Attivo
Finestre multiprocesso 0/0 Disattivato
Processi remoti 0 <#remote-processes>
Criteri a livello aziendale Disattivati
Chiave servizio Google Location Non presente
Chiave servizio Google Safebrowsing Non presente
Chiave per georilevazione di Mozilla Non presente
Modalità provvisoria false Account di posta e news
ID
Server in entrata Server in uscita
Nome Sicurezza della connessione Metodo di autenticazione
Nome Sicurezza della connessione Metodo di autenticazione Predefinito?
account1
(none) Local Folders plain passwordCleartext
account2
(exquilla) webmailex.cmbcarpi.it:443 SSL passwordCleartext
null plain passwordCleartext true
account3
(imap) imap.pec.actalis.it:993 SSL passwordCleartext
smtp.pec.actalis.it:465 SSL passwordCleartext true Segnalazioni di arresto
anomalo degli ultimi 3 giorni
ID segnalazione Inviata Processi remoti
Tipo Numero Estensioni
Nome Versione Attiva ID
Amazon.it 1.1 true amazon@search.mozilla.org
Attach from Clipboard 1.2.68 true clipboard@ganss.org
Bing 1.0 true bing@search.mozilla.org
Category Manager 3.5 true sendtocategory@jobisoft.de
DuckDuckGo 1.0 true ddg@search.mozilla.org
duplicateContactsManager 2.1.1 true duplicateContactsManager@ddvo.net
ExQuilla for Exchange 68.0.3 true exquilla@mesquilla.com
Google 1.0 true google@search.mozilla.org
ImportExportTools NG 4.0.4 true ImportExportToolsNG@cleidigh.kokkini.net
Lightning 68.1.2 true {e2fda1a4-762b-4020-b5ad-a41df1933103}
LocalFolders 2.0.2 true localfolder@philoux.eu
Manually sort folders 2.0.2 true tbsortfolders@xulforum.org
Provider Exchange ActiveSync 1.6 true eas4tbsync@jobisoft.de
quickFilters 4.2 true quickFilters@axelg.com
Quicktext 2.4 true {8845E3B3-E8FB-40E2-95E9-EC40294818C4}
Show All Body Parts 1.3.2 true ShowAllBodyParts@kamens.us
TbSync 2.5 true tbsync@jobisoft.de
Wikipedia (it) 1.0 true wikipedia@search.mozilla.org Grafica
Caratteristiche
Composizione Basic
Panoramica/zoom asincroni (APZ) nessuno
Informazioni driver WSI WebGL 1 EGL_VENDOR: Google Inc. (adapter LUID:
000000000000ca72) EGL_VERSION: 1.4 (ANGLE 2.1.0.8a050090f926)
EGL_EXTENSIONS: EGL_EXT_create_context_robustness
EGL_ANGLE_d3d_share_handle_client_buffer
EGL_ANGLE_d3d_texture_client_buffer
EGL_ANGLE_surface_d3d_texture_2d_share_handle
EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size
EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_NV_post_sub_buffer
EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image
EGL_KHR_image_base EGL_KHR_gl_texture_2D_image
EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image
EGL_KHR_get_all_proc_addresses EGL_KHR_stream
EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv
EGL_ANGLE_flexible_surface_compatibility
EGL_ANGLE_stream_producer_d3d_texture
EGL_ANGLE_create_context_webgl_compatibility
EGL_CHROMIUM_create_context_bind_generates_resource
EGL_EXT_pixel_format_float EGL_KHR_surfaceless_context
EGL_ANGLE_display_texture_share_group
EGL_ANGLE_create_context_client_arrays EGL_ANGLE_program_cache_control
EGL_ANGLE_robust_resource_initialization
EGL_ANGLE_create_context_extensions_enabled EGL_ANDROID_blob_cache
EGL_ANDROID_recordable EGL_EXTENSIONS(nullptr): EGL_EXT_client_extensions
EGL_EXT_platform_base EGL_EXT_platform_device EGL_ANGLE_platform_angle
EGL_ANGLE_platform_angle_d3d EGL_ANGLE_device_creation
EGL_ANGLE_device_creation_d3d11 EGL_ANGLE_experimental_present_path
EGL_KHR_client_get_all_proc_addresses EGL_KHR_debug
EGL_ANGLE_explicit_context
Renderer driver WebGL 1 Google Inc. -- ANGLE (Intel(R) HD Graphics 5500
Direct3D11 vs_5_0 ps_5_0)
Versione driver WebGL 1 OpenGL ES 2.0 (ANGLE 2.1.0.8a050090f926)
Estensioni driver WebGL 1 GL_ANGLE_client_arrays GL_ANGLE_depth_texture
GL_ANGLE_explicit_context GL_ANGLE_explicit_context_gles1
GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample
GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_memory_size
GL_ANGLE_multi_draw GL_ANGLE_multiview_multisample
GL_ANGLE_pack_reverse_row_order GL_ANGLE_program_cache_control
GL_ANGLE_provoking_vertex GL_ANGLE_request_extension
GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3
GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage
GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource
GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_color_buffer_float_rgb
GL_CHROMIUM_color_buffer_float_rgba GL_CHROMIUM_copy_compressed_texture
GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_func_extended
GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_marker
GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers
GL_EXT_float_blend GL_EXT_frag_depth GL_EXT_instanced_arrays
GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean
GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB
GL_EXT_shader_texture_lod GL_EXT_texture_compression_bptc
GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc_srgb
GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888
GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage
GL_KHR_debug GL_KHR_parallel_shader_compile
GL_KHR_robust_buffer_access_behavior GL_NV_EGL_stream_consumer_external
GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image
GL_OES_EGL_image_external GL_OES_compressed_ETC1_RGB8_texture
GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary
GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8
GL_OES_standard_derivatives GL_OES_surfaceless_context
GL_OES_texture_border_clamp GL_OES_texture_float
GL_OES_texture_float_linear GL_OES_texture_half_float
GL_OES_texture_half_float_linear GL_OES_texture_npot
GL_OES_vertex_array_object OES_compressed_EAC_R11_signed_texture
OES_compressed_EAC_R11_unsigned_texture
OES_compressed_EAC_RG11_signed_texture
OES_compressed_EAC_RG11_unsigned_texture OES_compressed_ETC2_RGB8_texture
OES_compressed_ETC2_RGBA8_texture
OES_compressed_ETC2_punchthroughA_RGBA8_texture
OES_compressed_ETC2_punchthroughA_sRGB8_alpha_texture
OES_compressed_ETC2_sRGB8_alpha8_texture OES_compressed_ETC2_sRGB8_texture
Estensioni WebGL 1 ANGLE_instanced_arrays EXT_blend_minmax
EXT_color_buffer_half_float EXT_disjoint_timer_query EXT_float_blend
EXT_frag_depth EXT_shader_texture_lod EXT_sRGB EXT_texture_compression_bptc
EXT_texture_filter_anisotropic OES_element_index_uint
OES_standard_derivatives OES_texture_float OES_texture_float_linear
OES_texture_half_float OES_texture_half_float_linear
OES_vertex_array_object WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture
WEBGL_draw_buffers WEBGL_lose_context
Informazioni driver WSI WebGL 2 EGL_VENDOR: Google Inc. (adapter LUID:
000000000000ca72) EGL_VERSION: 1.4 (ANGLE 2.1.0.8a050090f926)
EGL_EXTENSIONS: EGL_EXT_create_context_robustness
EGL_ANGLE_d3d_share_handle_client_buffer
EGL_ANGLE_d3d_texture_client_buffer
EGL_ANGLE_surface_d3d_texture_2d_share_handle
EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size
EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_NV_post_sub_buffer
EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image
EGL_KHR_image_base EGL_KHR_gl_texture_2D_image
EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image
EGL_KHR_get_all_proc_addresses EGL_KHR_stream
EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv
EGL_ANGLE_flexible_surface_compatibility
EGL_ANGLE_stream_producer_d3d_texture
EGL_ANGLE_create_context_webgl_compatibility
EGL_CHROMIUM_create_context_bind_generates_resource
EGL_EXT_pixel_format_float EGL_KHR_surfaceless_context
EGL_ANGLE_display_texture_share_group
EGL_ANGLE_create_context_client_arrays EGL_ANGLE_program_cache_control
EGL_ANGLE_robust_resource_initialization
EGL_ANGLE_create_context_extensions_enabled EGL_ANDROID_blob_cache
EGL_ANDROID_recordable EGL_EXTENSIONS(nullptr): EGL_EXT_client_extensions
EGL_EXT_platform_base EGL_EXT_platform_device EGL_ANGLE_platform_angle
EGL_ANGLE_platform_angle_d3d EGL_ANGLE_device_creation
EGL_ANGLE_device_creation_d3d11 EGL_ANGLE_experimental_present_path
EGL_KHR_client_get_all_proc_addresses EGL_KHR_debug
EGL_ANGLE_explicit_context
Renderer driver WebGL 2 Google Inc. -- ANGLE (Intel(R) HD Graphics 5500
Direct3D11 vs_5_0 ps_5_0)
Versione driver WebGL 2 OpenGL ES 3.0 (ANGLE 2.1.0.8a050090f926)
Estensioni driver WebGL 2 GL_ANGLE_client_arrays GL_ANGLE_copy_texture_3d
GL_ANGLE_depth_texture GL_ANGLE_explicit_context
GL_ANGLE_explicit_context_gles1 GL_ANGLE_framebuffer_blit
GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays
GL_ANGLE_lossy_etc_decode GL_ANGLE_memory_size GL_ANGLE_multi_draw
GL_ANGLE_multiview_multisample GL_ANGLE_pack_reverse_row_order
GL_ANGLE_program_cache_control GL_ANGLE_provoking_vertex
GL_ANGLE_request_extension GL_ANGLE_robust_client_memory
GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5
GL_ANGLE_texture_multisample GL_ANGLE_texture_usage
GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource
GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_color_buffer_float_rgb
GL_CHROMIUM_color_buffer_float_rgba GL_CHROMIUM_copy_compressed_texture
GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_func_extended
GL_EXT_blend_minmax GL_EXT_color_buffer_float
GL_EXT_color_buffer_half_float GL_EXT_debug_marker
GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers
GL_EXT_float_blend GL_EXT_frag_depth GL_EXT_instanced_arrays
GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean
GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB
GL_EXT_shader_texture_lod GL_EXT_texture_compression_bptc
GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc_srgb
GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888
GL_EXT_texture_norm16 GL_EXT_texture_rg GL_EXT_texture_storage
GL_EXT_unpack_subimage GL_KHR_debug GL_KHR_parallel_shader_compile
GL_KHR_robust_buffer_access_behavior GL_NV_EGL_stream_consumer_external
GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image
GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3
GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth32
GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_mapbuffer
GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives
GL_OES_surfaceless_context GL_OES_texture_border_clamp GL_OES_texture_float
GL_OES_texture_float_linear GL_OES_texture_half_float
GL_OES_texture_half_float_linear GL_OES_texture_npot
GL_OES_vertex_array_object GL_OVR_multiview2
OES_compressed_EAC_R11_signed_texture
OES_compressed_EAC_R11_unsigned_texture
OES_compressed_EAC_RG11_signed_texture
OES_compressed_EAC_RG11_unsigned_texture OES_compressed_ETC2_RGB8_texture
OES_compressed_ETC2_RGBA8_texture
OES_compressed_ETC2_punchthroughA_RGBA8_texture
OES_compressed_ETC2_punchthroughA_sRGB8_alpha_texture
OES_compressed_ETC2_sRGB8_alpha8_texture OES_compressed_ETC2_sRGB8_texture
Estensioni WebGL 2 EXT_color_buffer_float EXT_disjoint_timer_query
EXT_float_blend EXT_texture_compression_bptc EXT_texture_filter_anisotropic
OES_texture_float_linear WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info
WEBGL_debug_shaders WEBGL_lose_context
Usa Tiling (contenuti) true
Off Main Thread Painting attivo true
Conteggio worker Off Main Thread Painting 3
Obiettivo per frequenza fotogrammi 60
DirectWrite true (6.2.9200.22164)
GPU #1
Attivo Sì
Descrizione Intel(R) HD Graphics 5500
ID produttore 0x8086
ID dispositivo 0x1616
Versione driver 10.18.14.4099
Data aggiornamento driver 1-19-2015
Driver igdumdim64 igd10iumd64 igd10iumd64 igdumdim32 igd10iumd32 igd10iumd32
ID sottosistema 06321028
RAM Sconosciuto
Diagnostica
AzureCanvasBackend skia
AzureContentBackend skia
AzureFallbackCanvasBackend cairo
Parametri ClearType Gamma: 1,8 Pixel Structure: RGB ClearType Level: 100
Enhanced Contrast: 50
Registro decisioni
HW_COMPOSITING
disabled by user: Disabled by pref
D3D11_COMPOSITING
unavailable by default: Hardware compositing is disabled
DIRECT2D
unavailable by default: Direct2D requires Direct3D 11 compositing
D3D11_HW_ANGLE
unavailable by default: D3D11 compositing is disabled
disabled by env: D3D11 compositing is disabled
GPU_PROCESS
unavailable by default: Multi-process mode is not enabled
WEBRENDER
opt-in by default: WebRender is an opt-in feature
unavailable-no-angle by runtime: ANGLE is disabled
WEBRENDER_QUALIFIED
blacklisted by env: No qualified hardware Media
Back-end audio wasapi
Numero massimo di canali 2
Frequenza di campionamento preferita 48000
Dispositivi di output
Nome Gruppo Produttore Stato Preferito Formato Canali Frequenza Latenza
Altoparlanti / cuffie (Realtek High Definition Audio)
HDAUDIO\FUNC_01&VEN_10EC&DEV_0255&SUBSYS_10280632&REV_1000\4&1213004d&0&0001
Enabled All default: F32LE, support: S16LE F32LE 2 default: 48000, support:
48000 - 48000 144 - 480
Dispositivi di input
Nome Gruppo Produttore Stato Preferito Formato Canali Frequenza Latenza
Missaggio stereo (Realtek High Definition Audio)
HDAUDIO\FUNC_01&VEN_10EC&DEV_0255&SUBSYS_10280632&REV_1000\4&1213004d&0&0001
Disabled None default: F32LE, support: S16LE F32LE 2 default: 48000,
support: 48000 - 48000 0 - 0
Microfono jack (Realtek High Definition Audio)
HDAUDIO\FUNC_01&VEN_10EC&DEV_0255&SUBSYS_10280632&REV_1000\4&1213004d&0&0001
Unplugged None default: F32LE, support: S16LE F32LE 2 default: 48000,
support: 48000 - 48000 0 - 0
Gruppo microfoni (Realtek High Definition Audio)
HDAUDIO\FUNC_01&VEN_10EC&DEV_0255&SUBSYS_10280632&REV_1000\4&1213004d&0&0001
Enabled All default: F32LE, support: S16LE F32LE 2 default: 48000, support:
48000 - 48000 144 - 480 Preferenze importanti modificate
browser.cache.disk.amount_written 176360
browser.cache.disk.capacity 522240
browser.cache.disk.filesystem_reported 1
extensions.lastAppVersion 68.1.2
font.name.monospace.el Consolas
font.name.monospace.x-cyrillic Consolas
font.name.monospace.x-unicode Consolas
font.name.monospace.x-western Consolas
font.name.sans-serif.el Calibri
font.name.sans-serif.x-cyrillic Calibri
font.name.sans-serif.x-unicode Calibri
font.name.sans-serif.x-western Calibri
font.name.serif.el Cambria
font.name.serif.x-cyrillic Cambria
font.name.serif.x-unicode Cambria
font.name.serif.x-western Cambria
font.size.fixed.el 14
font.size.fixed.x-cyrillic 14
font.size.fixed.x-unicode 14
font.size.fixed.x-western 14
font.size.variable.el 17
font.size.variable.x-cyrillic 17
font.size.variable.x-unicode 17
font.size.variable.x-western 17
idle.lastDailyNotification 1571646350
layers.mlgpu.sanity-test-failed false
media.gmp.storage.version.observed 1
media.hardware-video-decoding.failed false
network.automatic-ntlm-auth.trusted-uris https://webmailex.cmbcarpi.it
network.cookie.prefsMigrated true
network.predictor.cleaned-up true
places.database.lastMaintenance 1571215544
places.history.expiration.transient_current_max_pages 112348
print.always_print_silent false
security.sandbox.content.tempDirSuffix
{93e9aeea-9e44-490c-88aa-e10ad0166f6b}
security.sandbox.plugin.tempDirSuffix {0443bf7c-f654-427f-ae05-db4d76ef41fb}
signon.importedFromSqlite true
storage.vacuum.last.index 1
storage.vacuum.last.places.sqlite 1570550554 Preferenze importanti
bloccate Database
Places JavaScript
GC incrementale true Accessibilità
Attivato false
Blocca servizi accessibilità 0
Handler accessibilità utilizzato false
Istanziatore accessibilità
Versioni librerie

Versione minima previstaVersione in uso
NSPR 4.21 4.21
NSS 3.44.1 3.44.1
NSSSMIME 3.44.1 3.44.1
NSSSSL 3.44.1 3.44.1
NSSUTIL 3.44.1 3.44.1 Sandbox
Livello sandbox content process 0
Livello effettivo sandbox content process 1 Internazionalizzazione e
localizzazione
Impostazioni dell’applicazione
Lingue richieste ["it"]
Lingue disponibili ["it","en-US"]
Lingue applicazione ["it","en-US"]
Impostazioni internazionali ["it-IT"]
Lingua predefinita "it"
Sistema operativo
Lingue del sistema ["it-IT"]
Impostazioni internazionali ["it-IT"]

Build platform


      target


      i686-pc-mingw32

  Build tools


      Compiler
      Version
      Compiler flags


      z:/task_1570551612/build/src/clang/bin/clang-cl.exe -Xclang
-std=gnu99 -m32
      8.0.0
      -fcrash-diagnostics-dir=z:/task_1570551612/public/build
-nologo -D_HAS_EXCEPTIONS=0 -guard:cf -W3 -Gy -Zc:inline -arch:SSE2 -Gw
-Wno-unknown-pragmas -Wno-ignored-pragmas -Wno-deprecated-declarations
-Wno-invalid-noreturn


      z:/task_1570551612/build/src/clang/bin/clang-cl.exe -m32
      8.0.0
      -Qunused-arguments -guard:cf -Qunused-arguments
-fcrash-diagnostics-dir=z:/task_1570551612/public/build -TP -nologo
-Zc:sizedDealloc- -D_HAS_EXCEPTIONS=0 -guard:cf -W3 -Gy -Zc:inline
-arch:SSE2 -Gw -Wno-inline-new-delete -Wno-invalid-offsetof
-Wno-microsoft-enum-value -Wno-microsoft-include -Wno-unknown-pragmas
-Wno-ignored-pragmas -Wno-deprecated-declarations -Wno-invalid-noreturn
-Wno-inconsistent-missing-override -Wno-implicit-exception-spec-mismatch
 -Wno-unused-local-typedef -Wno-ignored-attributes
-Wno-used-but-marked-unused -D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING
 -GR- -Z7 -O2 -Oy-


      z:/task_1570551612/build/src/rustc/bin/rustc.exe
      1.34.0


  Configure options

MOZ_AUTOMATION=1 'MOZILLABUILD=C:\mozilla-build'
--enable-application=comm/mail --target=i686-pc-mingw32
MOZILLA_OFFICIAL=1 --enable-update-channel=release
VC_PATH=z:/task_1570551612/build/src/vs2017_15.8.4/VC CC=clang-cl
CXX=clang-cl
WINDOWSSDKDIR=z:/task_1570551612/build/src/vs2017_15.8.4/SDK
'DIA_SDK_PATH=z:/task_1570551612/build/src/vs2017_15.8.4/DIA SDK'
LINKER=lld-link MAKECAB=z:/task_1570551612/build/src/makecab.exe
NASM=z:/task_1570551612/build/src/nasm/nasm.exe ENABLE_CLANG_PLUGIN=1
--enable-calendar RUSTC=z:/task_1570551612/build/src/rustc/bin/rustc
CARGO=z:/task_1570551612/build/src/rustc/bin/cargo
RUSTDOC=z:/task_1570551612/build/src/rustc/bin/rustdoc
CBINDGEN=z:/task_1570551612/build/src/cbindgen/cbindgen
RUSTFMT=z:/task_1570551612/build/src/rustc/bin/rustfmt
LLVM_CONFIG=z:/task_1570551612/build/src/clang/bin/llvm-config
--enable-js-shell NODEJS=z:/task_1570551612/build/src/node/node.exe
--enable-rust-simd MAKE=z:/task_1570551612/build/src/mozmake.EXE
--enable-crashreporter --enable-official-branding

**Comment by cleidigh** [comment] 2019-10-23 05:23
@andredimu 
the debug console is accessed using 'Shift-Control-J'
then you want to look for errors or warnings.
since you are set up is very similar to mine it should possible to reproduce
does the screenshot I sent you represent you are not able to see?

**Comment by andredimu** [comment] 2019-10-23 07:38
Hi,
the screenshots#1 is the preview message in Inbox folder, the screenshots#2 in the output pdf (not all recipients in to:... and Cc:... field). If the export is made from local folders, all recipients are correctly listed in the pdf file

![Screenshot_#1](https://user-images.githubusercontent.com/56824807/67368855-50ae6d80-f578-11e9-98cd-077bceca1c30.jpg)

![Screenshot_#2](https://user-images.githubusercontent.com/56824807/67368879-5b690280-f578-11e9-9022-e78c599e462c.jpg)

Here the debug 
[debug.txt](https://github.com/thundernest/import-export-tools-ng/files/3760813/debug.txt)

**Comment by cleidigh** [comment] 2019-10-23 18:34
@andredimu 
thanks, that's clear.  Only the first 'To' contact , same for 'CC'
Also I understand if you were to print this exact same e-mail after moving it to a local folder , that would show all the names, yes?

I will continue to do some investigation.  Probably I will need to point you to some tests that could  give us more feedback.  I will let you know.

**Comment by andredimu** [comment] 2019-10-23 19:17
Yes is correct, in local folder I have no problem.
Thank you for the help.

**Comment by cleidigh** [comment] 2019-10-26 05:20
@andredimu 
my initial testing and investigation hasn't turned up anything obvious, or even given me any ideas yet.
the big problem is that I cannot reproduce it.
But I will keep you posted

**Comment by andredimu** [comment] 2019-10-26 22:43
Thank you.
I think the problem is general concerning the printing process. if I print a message from the inbox I have the same problem, only the first 'To' contact and same for 'CC' are shown in the header. Instead the header is complete if I print a message from a local folder.
But I haven't found any bug reports of this kind in thunderbird issues

**Comment by cleidigh** [comment] 2019-10-27 04:46
@andredimu 
That makes some sense, I could not find anything that would change this behavior.  I will look in the bug list also.  I will make a new one if it doesn't exist.
Thanks for experimenting!

**Comment by andredimu** [comment] 2019-11-05 16:03
The problem only occurs with the ExQuilla addon for Microsoft Exchange Server. 
With other addon for Exchange or with "classic" email accounts,  everything works well. Closed

**Closed** 2019-11-05 16:04 UTC
