### ISSUE TITLE
Seamonkey should be supported

### ISSUE THREAD

**Issue by dipgithub** [thundernest/import-export-tools-ng#94] opened 2020-03-28 11:46 UTC
The present version of the extension cannot be installed in Seamonkey without amendment. Since the extension still supports Tunderbird 60 it can be installed in Seammonkey by adding 

        <em:targetApplication>
          
          <Description>
            <em:id>{92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}</em:id>
            <em:minVersion>2.0</em:minVersion>
            <em:maxVersion>2.*</em:maxVersion>
          </Description>
        </em:targetApplication>

into install.rdf.

Since I use Seamonkey because I need some further extensions which do no longer work with Thunderbird 68, it would be great if the above code could be added to the current version of ImportExportTools NG.

**Comment by cleidigh** [comment] 2020-03-28 18:50
@dipgithub 
Ahh.  That is tricky.  It is currently very difficult to continue to maintain 60,68 and going forward.
SeeMonkey is quite behind Thunderbird and in discussions with core team (I am actually a volunteer team member focusing on extension support), see monkey is pretty much considered abandoned.
The problem is if I add Seamonkey to the install.rdf I am declaring compatible when I do no testing 
or infective zero interaction with SM.  
What I could do is to make an unofficial version in the repository (not ATN) with a "as is " Warning
but I would.to any changes other than the install file.  Hopefully this is a satisfactory workaround as long as it continues to work for you.  

a couple of notes and questions:
- what extensions are you lacking for 68 compatibility?  as I said part of my job is working with developers to transition.
- While it is a longer-term goal I will be working on bringing in the features of import export tools
into Thunderbird core.  For this I would like to get as much user feedback as possible.
- would you mind telling me your use case and what's important to you?

Interested in your feedback the above...
@cleidigh

**Comment by dipgithub** [comment] 2020-03-28 19:47
@cleidigh 
Thanks, if it is too much effort to maintain an unofficial version, this is not really necessary since I can always add the above lines to install.rdf on my end.

In fact, I hoped you would ask why I use Seamonkey instead of Thunderbird :-)

I personally use Thunderbird on Linux Mint on my home computer for years but in our office we only recently tried to switch our computer which receives all incoming mails from Outlook (running on Windows) to Linux and a Linux compatible mail programm for security reasons. I recommended Thunderbird and Linux Mint and now it is my job to get everything running smoothly :-)

I first tried (of course) Thunderbird but found that there are two important features which can only be realized with extensions (at least at the moment) which are no longer compatible with Thunderbird (but with Seamonkey).

The first extension is PrintingTools. In fact, similar to ImportExportTools we need only one specific feature of this tool, namely inserting the attachment's list at the header of a message, just after the recipients (when the message is printed). By default Thunderbird prints the attachment's list at the very end of the message. I have to admit that we still print all incoming emails (since we still have paper files). But at least we try not to print that pages of an e-mail which comprise the part of the previous conversation. That means we print only the newest part of the e-mail conversation (which can be only the first page out of a lot of pages). Unfortunately, the attechment's list is on the last page and will thus not be printed. That means that you do not recognize on the printout of the first page if there was an attachment or not. For this reason it is very important for us to have the attachment's list on the first page, preferably at the end of the header. And btw, this facilitates a user to switch from Outlook to Thunderbird since it is exactly the way Outlook does it and it is always easier to switch if the new program behaves somewhat similar as the old one.

The second extension is Dorando Keyconfig or a similar tool which allows to rebind keyboard shortcuts and to add keyboard shortcuts to functions which have no shortcut by default. Working with keyboard shortcuts is often much faster and e.g. Print Preview has no shortcut assigned in Thunderbird by default, so I assigned Strg-Shift-P with Dorando Keyconfig.

BTW, I would love to be able to assign a keyboard shortcut to the feature "Save only the index of the selected messages" of ImportEportTool NG, because at the moment you have to right click on the selection, move the mouse to menu item "Save selected messages" move the mouse to "just index (HTML)" and then click on it (which is quite annyoing). But this is probably not even possible with Dorando Keyconfig (but if you could include a "hidden" shortcut for that I would really appreciate that.... ;-)).

Do you also whish to hear bug reports or feature requests for Thunderbird in general (not extension related)? Because I had two.

**Comment by cleidigh** [comment] 2020-03-28 21:17
@dipgithub 
all good stuff thanks! of couple of quick points I may have more later:
- I might do a big fat warning on the sea monkey compatibility (what you see is what you get)
- printing tools is also by Paolo K, I have been trying to see if I can get the time to look at the complexity of converting printing tools myself
- D Keyboard config is also interesting to me as I am disabled and have to do everything by voice which requires keyboard shortcuts for everything, Thunderbird keyboard handling is awful!
there is possibility Jonathan Kamans will update this as he got a kick starter campaign going to help fund all the work.
feel free to comment on bugs and improvements.

**Comment by dipgithub** [comment] 2020-03-28 21:30
@cleidigh 
I do not know if printing tools work in 60.9. I know that it works in Seamonkey 2.53.1 which is based on Thunderbird 60. But I do not know on which subversion of 60. On the add-on page of printing tolls it is stated that it works with Thunderbird 3.0 - 60.*

**Comment by dipgithub** [comment] 2020-04-01 11:07
@cleidigh 
Fortunately, a colleague found out that with an indiviual userContent.css which must be stored in the chrome folder of the Thunderbird profile it is possible to change the layout of a printed message. He was finally able to move the attachment's list to the bottom of the header which means that we do no longer need the PrintingTools add-on.

That means that we can switch from Seamonkey to Thunderbird using your amended ImportExportTools NG for the desired index creation.

The only missing point is now that we cannot use Dorando Keyconfig for defining the shortcut Ctrl-Shift-P for PrintPreview. Since you just added the shortcut Ctrl-Shift-D to your add-on, by adding 

```
<keyset >
  <key id="index-key" modifiers="control shift" key="D" oncommand="exportSelectedMsgs(5)"/>
</keyset>
```

to mboximport.xul, would it be possible to add the shortcut Ctrl-Shift-P for PrintPreview in a similar way? I tried to add the line

 ` <key id="index-key" modifiers="control shift" key="P" oncommand="printpreview"/>`

but unfortunately this did not work. You do not have to add this to your official version but if you could give me a hint how this additional shortcut could be added correctly I would simply make the necessary amendment to our individual version of the add-on.

Thank your very much for your continued support!

**Comment by cleidigh** [comment] 2020-04-21 22:13
@dipgithub 
I would like to go ahead and close this as well as #95 
since I am not going to be supporting Seamonkey
@cleidigh

**Comment by dipgithub** [comment] 2020-04-21 23:46
@cleidigh 
Since we finally were able to switch from Seamonkey to Thunderbird (due to your support) I have no problems with that.

**Closed** 2020-04-27 23:41 UTC
