### ISSUE TITLE
Problem with importing folder with spaces in names

### ISSUE THREAD

**Issue by vincentkoevoets** [thundernest/import-export-tools-ng#372] opened 2022-12-31 12:31 UTC
Hello, 
I think I've found an issue with the importing of mbox files with their respective subfolders. When I try to import an mbox file, it imports fine, even with subfolders in the folder.sbd/subfolder format. But when there is a space in the main folders name, the program only imports the main folder and not its subfolders. I will try to put it more clearly:

This imports fine, with subfolders too (with filenames mainfolder, mainfolder.sbd/subfolder1, mainfolder.sbd/subfolder2):
- mainfolder
|- subfolder1
|- subfolder2

This only imports main with space (with filenames main with space, main with space.sbd/subfolder1, main with space.sbd/subfolder2):
- main with space
|- subfolder1
|- subfolder2

I've tried all this with a backup generated by ImportExportToolsNG itself. When I try to import the subfolders manually, it works but of course this is extra work. 
Is there anything I'm missing? 

EDIT
All of the above was done on a Linux box. Figured I'd try it in Windows and it does seem to work properly there. So I'll be using Windows for restoring if I need it.

**Comment by cleidigh** [comment] 2022-12-31 20:46
@vincentkoevoets 
Happy New Year!
I am surprised as folders with spaces are pretty typical, however, since this does work on Windows there may be a quirk on Linux.
Can you id os,tb and IETNG versions?
I have a Mint 23 VM I can test.
@cleidigh

**Comment by vincentkoevoets** [comment] 2023-01-03 08:31
I'm on Chrome OS so I use the build in Linux VM, which is Debian 11. That is where I installed Thunderbird, which is version 102.6.0 and IETNG version 12.0.2. But today, the problem seems to have resolved itself. I tried again importing a bunch of nested mbox files, and all is imported correctly. So I don't know what happened before, but this seems to be resolved.

**Comment by cleidigh** [comment] 2023-01-03 19:51
@vincentkoevoets 
Well that is good news especially as I would not be able to reproduce your environment!
Do you think we can close this?
@cleidigh

**Closed** 2023-01-09 19:06 UTC

**Comment by vincentkoevoets** [comment] 2023-01-10 04:21
I'm sorry for not replying anymore. But closing is fine, I think this was a fluke since everything is working fine now.
