### ISSUE TITLE
i would like to ask for support for the import export tools. bulk e-mail export, etc

### ISSUE THREAD

**Issue by yoshusawkalay** [thundernest/import-export-tools-ng#356] opened 2022-11-05 18:48 UTC
I've seen these options: export as zip, and an option in different formats. One as a format seems possible: HTML with attachments. However, I am unable to find out from mozilla if it is as individual e-mails or like showing many in one file. I also don't know where the links in the HTML files are stored. I have read somewhere that not all attachments show up.

I had confused POP mail and accidentally downloaded all e-mails pretty much. I want to back up the e-mails that I downloaded, and be able to view them. Please advise how I can backup those e-mails and be able to view them together with attachments. Thanks.

**Comment by cleidigh** [comment] 2022-11-05 20:28
@yoshusawkalay 
You have several questions and perhaps goals. I will start by basic answers and You can follow up.

First backup versus moving or saving messages in local folders.
Backing up messages in a traditional sense usually means having them outside of Thunderbird possibly viewable by something like a browser. The export to HTML with the attachments is one example.  This case is one way, you couldn't re-import the messages. If you want to export to EML or mbox ( single message files or grouped messages) these could be reimported, but not directly viewable.

To keep the messages within Thunderbird you can copy or move your messages to one or more local folders which keeps them managed by yourself, Thunderbird will not touch them regardless of your accounts. They are viewable and their attachments as as well.

If you export to HTML the messages are saved as individual files with an attachment link to each file. There is a bug with utf8 attachment folders that I have a beta fix, however, this only affects users who need non latin or accented characters in the attachment folders.

I suggest experimenting, non of the export operations are destructive.

@cleidigh

**Comment by yoshusawkalay** [comment] 2022-11-05 21:36
if they are exported, it would be helpful to view any attachments. sometimes it is necessary to access those files and emails, for some reason, and communicate with someone about them. It may be possible to copy content from an external source to a new e-mail, if it is saved into a file that is not just HTML format. If it is HTML format, and any attachments are separate, that is possible. For MBOX formats, what does it mean that they are not directly viewable?

Originally, the goal was to have some e-mails within an e-mail platform, but back them up, and still have a source to view them, and have records, and possibly import them, if necessary. However, I will need to have something to view them and access them, due to my mistake if possible. websites and HTML viewers I don't know if there is a storage place offline with these. Logically, it would need to store files on my own system. if somebody sent me a project file or something, i would need to know how this is being stored. So also, I am trying to figure out that if Thunderbird had downloaded tons of emails, how are these going to be saved (as well as the attachments)? Again, please help me know about the e-mails not being directly viewable. I like the idea of having a batch export (or whatever), but being able to view all of them, and I have many e-mails that were downloaded by POP. I don't want to save them as individual e-mails if I don't have to.

**Comment by cleidigh** [comment] 2022-11-06 19:11
@yoshusawkalay 
I think you should try exporting a small folder to HTML with attachments and you will see the structure and the attachment links in the messages.

The export to mbox files essentially makes a duplicate of the internal TB files, but then they are not visible to TB so they are no longer directly viewable.
@cleidigh

**Comment by yoshusawkalay** [comment] 2022-11-06 22:24
Do you mean that I should experiment with a subfolder? If mbox files are not directly viewable, what are they? How are they viewable?

**Comment by cleidigh** [comment] 2022-11-06 22:49
@yoshusawkalay 
Yes right click on a folder in the tree and you will get the export options.
The mbox files are viewable when they are within TB, once exported TB does not know about them.

**Comment by cleidigh** [comment] 2022-11-06 23:38
Mbox files are a set of emails from a folder. EML files are a single message. EML files can be individually opened and viewed. Mbox files can only be viewed when they are within the TB database.

**Comment by yoshusawkalay** [comment] 2022-11-08 22:18
so, i should check the size of the subfolders first. I am not sure if the MBOX files can be put back into Thunderbird or not, because I think somebody said they can be. I just didn't see a clear option to do that. I will test exporting a small folder, yet I would like to export a backup copy of at was loaded (which is a lot of e-mails). I am not sure if some program can view those if it is MBOX format.

**Comment by yoshusawkalay** [comment] 2022-11-08 22:24
so it seems good for a small amount, but yet i see the several files. please let me know about if MBOX format can be viewed/re-imported. What I see as a potential option is something like a compressed file like jzip if not.

**Comment by yoshusawkalay** [comment] 2022-11-10 16:22
hi, i am wondering if anybody is able to follow up with me? I don't understand specifically if MBOX files can be reimported back into Thunderbird when exported, since Thunderbird is a shell program, and downloads e-mails. Or is there a third-party program to view the e-mails? My only other thoughts are to compact files another way. I want to export many e-mails that might be too many to export individually.

**Comment by cleidigh** [comment] 2022-11-10 17:20
@yoshusawkalay 
Yes mbox files can be both exported and reimported. This is the native format that Thunderbird uses storing emails in one file per folder.

I think that you may be thinking about the backup as something "live".
I believe you may want separate the two goals.

First for viewing copy your emails to a local folder within Thunderbird .This allows you to view the emails normally.

Additionally for true backup you can export to mbox which can be saved anywhere offline and for any reason they can be reimported.
@cleidigh

**Comment by yoshusawkalay** [comment] 2022-11-10 22:02
I understand Thunderbird as another shell program. If it is POP mail, then the POP mail it stored there and it isn't deleted unless it is chosen by the user. However, it is not on the server. If it is IMAP, it is stored on the server while in Thunderbird, but deleted in both if one is. If I export something, but delete it from my account, how might it be imported again? Can you explain how to export the MBOX format, and how to import them again?

I also want to know how I can bulk export a lot of e-mails? For instance, 1,000? I didn't want to download a lot and not have them available on the server, but basically, that is what i need to do now.

**Comment by cleidigh** [comment] 2022-11-13 18:18
@yoshusawkalay 
First I suggest reading the help as it describes each menu function.

For mbox export : 
Aggregate all the emails you want to export in a local folder 
Now right click on that folder 
Choose IETNG \ Export folder
Choose where to save
this will save a single mbox file 

For re-import : 
Right click on the folder you want to import to
Choose Import mbox file 
Choose the mbox file you exported before 

@cleidigh

**Comment by yoshusawkalay** [comment] 2022-11-14 03:31
I am confused about this process. Earlier, I exported this today. It froze during the process. I tried to imitate it later, and it said it exported it, but there isn't a file. Also, all of the files that were produced are the inbox. These were from a POP e-mail account. I am not sure if they included the subfolders from the account. When I created the POP mail, it did not show the subfolders. I am seeing that some e-mails that were directed to those folders are in that POP mail account's downloaded e-mails. 

If I were to re-import those e-mails, where would they be imported to? I understand that you are talking about putting them into a folder, but the structure of the setup is an IMAP account, so they are based on a server now. How does thunderbird set the MBOX file so they are offline to view?

**Comment by cleidigh** [comment] 2022-11-16 20:12
@yoshusawkalay 
I am getting confused as you make some unclear statements.

First for basics please id the os, tb and IETNG versions.

Second we still are unclear that we are talking about accomplishing the same thing.
Exporting for backup and the ability to "view" the exported files are distinct.

When you exported what type did you do?
For simplicity I suggested a single folder export to mbox, no subfolders.
So if you copy all messages to a local folder you can export that folder to a single exported mbox which can later be reimported to view or use within TB.
If you want to continue viewing the messages then keep the local folder and the messages remain in TB
I think that is what you want, yes?
@cleidigh

**Comment by yoshusawkalay** [comment] 2022-11-17 19:23
i used the export option. Then export folder. It then exported a 1.5 gb inbox file. Actually a little larger. I have read some article that if the size of the mailbox might be larger, I may need to do something different, but I don't remember specifically.

That file is probably an MBOX file as it is inaccessible. I am wondering if there is a way to view them outside of Thunderbird, but since Thunderbird seems to operate by accessing a server, I wonder how putting them back in Thunderbird when the messages in Thunderbird are deleted is possible.

**Comment by cleidigh** [comment] 2022-11-18 22:43
@yoshusawkalay 
Yes what you exported is an mbox file.
If you want to view it you would have to re-import to a local folder. That way the server wouldn't do anything to the messages in the local folder.
There might be some software for viewing mbox files out there.

Unless you have some reason not to, my suggestion is still copy what you want viewable into your local folders and keep it in TB.
For backup export that and consider that an offline backup.
@cleidigh

**Comment by yoshusawkalay** [comment] 2022-11-18 23:38
what does "local folder" mean? Because for me, to remove excess space is to delete the files from the server after creating that mbox file. I am not sure what a local folder is, since there is the inbox, and the subfolders that are created within the interface of the web service interface.

**Comment by cleidigh** [comment] 2022-11-20 19:57
@yoshusawkalay 
Sorry I assumed you were familiar with Local Folders.

Thunderbird starts with an empty pseudo account in the folder tree. Under LF you can create subfolders. LF folders are stored within your profile unless changed. Thes folders can be used to store messages however you wish. These folders differ from account folders in that they are independent of any account and TB does not manipulate the messages.

The big thing in your case is that the messages are both viewable and searchable. To be extra clear, they are NOT stored on any server.

So in your last post you mentioned for the first time wanting to save space on the server.  This is is why I suggest moving the messages off the server into one or more local folders. This will save your server space, but allow you to use or view the messages.

If you also want an offline backup you can also export them as well.

I think now this would accomplish your goals.
@cleidigh

**Comment by yoshusawkalay** [comment] 2022-11-20 22:20
why would the subfolder appear on the website, when i create it under the account profile in thunderbird? then i delete it on the website, and it still is in thunderbird? At first, when I tried to create the folder, it seemed to indicate that there was no place to create a subfolder, but let me create one anyways. However, like I said, a folder was created on the website.

**Comment by cleidigh** [comment] 2022-11-20 22:24
Local folders do not get created on the server. To create them you right click on LF and add subfolder.

**Comment by yoshusawkalay** [comment] 2022-11-20 22:43
I see that now. It is at the bottom.. Is there ever a problem with exporting sent items? I read that there was a 4mb size limit previously. Also, importing them can be problematic.

**Comment by cleidigh** [comment] 2022-11-20 23:04
There is a 4GB file size limit.
Export from sent is no problem.
Imports to imap folders is problematic because this causes major sync issues.
@cleidigh

**Closed** 2022-12-08 02:50 UTC
