### ISSUE TITLE
Export directories browse location not saved in input field ( duplicate #275)

### ISSUE THREAD

**Issue by TeslaMagic** [thundernest/import-export-tools-ng#318] opened 2022-05-03 18:35 UTC
ImportExportTools NG v11.1 appears to work fine with the Thunderbird v100 and v101 candidates (using manifest change).

There is an issue with the "Export directories" Browse function (at least in Linux). You can click on Browse and select a folder/directory, but the selected does not get placed into the appropriate box. You can manually copy and paste the folder/directory locations into the "Export as MBOX file" and "Export selected messages" boxes but the "Export folders as single files" will not accept anything.

With the release of Thunderbird v102 on June 28th, it would be great if this was fixed.

Thank you.

**Comment by TeslaMagic** [comment] 2022-05-27 18:00
This is just a workaround...

I have gotten all of this to work by editing the Thunderbird prefs.js directly. The "Export folders as single files" entry works as well.

**Comment by cleidigh** [comment] 2022-06-15 23:45
@TeslaMagic 
I have started the new release for 102 Track:
- #324 
@cleidigh

**Comment by TeslaMagic** [comment] 2022-06-17 23:49
To reply to your question; "Also what pref did you change?"

The "Browse" buttons under "Export directories" do not function (at least in Linux). You can select a folder but it does not enter them into the dialog boxes. I've attached a screenshot showing the dialog box after I manually entered the directories into the TB prefs.js file.

I could manually copy the directory locations into the dialog boxes - all but one - "Export folders as single files". That one I had to enter manually into the prefs file.

Here are all the TB v91.10.0 (64-bit) prefs.js entries for Import-Export-Tools-NG:

user_pref("extensions.importexporttoolsng.autobackup.save_mode", -1);
user_pref("extensions.importexporttoolsng.export.filename_pattern", "%s-%D-%e");
user_pref("extensions.importexporttoolsng.export.use_container_folder", false);
user_pref("extensions.importexporttoolsng.exportEML.dir", "/home/mint/Downloads");
user_pref("extensions.importexporttoolsng.exportEML.filename_format", 2);
user_pref("extensions.importexporttoolsng.exportEML.use_dir", true);
user_pref("extensions.importexporttoolsng.exportMBOX.dir", "/home/mint/Downloads");
user_pref("extensions.importexporttoolsng.exportMBOX.use_dir", true);
user_pref("extensions.importexporttoolsng.exportMSG.dir", "/home/mint/Downloads");
user_pref("extensions.importexporttoolsng.exportMSG.use_dir", true);
user_pref("extensions.importexporttoolsng.printPDF", false);

The lines containing "/home/mint/Downloads" are the ones I either modified or added.

This is only for the Linux version of Thunderbird. I have not tested Windows or Mac.

Thank you for this extension/add-on! It's the most important one, in my opinion.

![Export Directories](https://user-images.githubusercontent.com/16181192/174413365-e891fde7-0bff-4335-9614-3f1e4c9489bd.png)

**Comment by cleidigh** [comment] 2022-06-18 01:13
@TeslaMagic 
Thanks for the clarity.
I can reproduce the issue on Windows and also see the inability to set manually the single file field.
I will do my best to sove in v12, probably not a biggie.
@cleidigh

**Comment by cleidigh** [comment] 2022-06-18 03:50
@TeslaMagic 
This turns out to be a duplicate of #275 
Fortunately @jobisoft already fixed this.
I will post first beta including this shortly.
Track in #324 
@cleidigh

**Comment by TeslaMagic** [comment] 2022-06-18 18:07
I tried to install v11.2 (TB91) (referenced in #275) into TB 91.0, way back, and it came up as incompatible. I disabled compatibility checking and it still would not install. Did manifest changes too. I tried with following TB releases with no luck, so I gave up.

Maybe I missed something. This doesn't really matter anymore since v12.0 is on its way.

**Comment by cleidigh** [comment] 2022-06-25 19:16
@TeslaMagic 
There are several things for 102 I have fixed in the first beta.  I should be able to post later today.
@cleidigh

**Comment by cleidigh** [comment] 2022-06-25 22:52
@TeslaMagic 
You can track and get the v12 beta from the release status issue : 
- #324 

This works in both 91 and 102
@cleidigh

**Comment by cleidigh** [comment] 2022-07-02 19:34
Fixed with v12

**Closed** 2022-07-02 19:34 UTC
Labels: bug, export
