### ISSUE TITLE
Export as CSV comes out as HTML

### ISSUE THREAD

**Issue by jrmarsh** [thundernest/import-export-tools-ng#23] opened 2019-09-30 20:50 UTC
Right Click --> ImportExportTools NG --> Export all messages in folder --> Spreadsheet (CSV) produces an output file in a HTML format not a CSV format!  Sample file attached (but renamed from .csv to .txt so GitHub will let me upload it.  Any help you can provide would be appreciated!
------------------------------------------------------------------------------
[index.csv.txt](https://github.com/thundernest/import-export-tools-ng/files/3673373/index.csv.txt)

**Comment by cleidigh** [comment] 2019-10-01 05:07
@jrmarsh 
Thanks for posting.  What version are you using? Thunderbird/ImportExportTools NG
I will also look to reproduce.

**Comment by jrmarsh** [comment] 2019-10-01 16:25
Thanks for investigating.  (And more importantly thanks for taking over development of this great utility in the first place!)  You probably don't need it now and I feel silly for not including it in the first place but Thunderbird 68.1.1 & ImportExportTools NG 4.0.4

**Comment by cleidigh** [comment] 2019-10-02 02:38
@jrmarsh 
I am kicking myself because this was supposed to be addressed by 4.0.4 which was outputting plaintext as HTML as well.  The formatter API change caused the bug.  I am sure I did a full search for all instances of the converter.  So either my search functions or my brain are at fault (probably the latter)  Since I adopted this out on I am still playing catch-up.  bear with me.

I just posted a beta XPI, 4.0.5-b1  if you're up for giving it a test drive and reporting back ;-)
I'd like to wait a few days before releasing to see if there's anything else.
Thanks again for reporting/your support!
@cleidigh 

https://github.com/thundernest/import-export-tools-ng/blob/csv-output-issue/xpi/import-export-tools-ng-4.0.5-b1-tb.xpi

**Comment by jrmarsh** [comment] 2019-10-02 16:18
Installed and tested it out this morning and works like a champ!  Thanks for fixing this and so quickly too!

**Comment by cleidigh** [comment] 2019-10-02 20:31
@jrmarsh 
that's great thanks.  I'm going to wait a few more days to see if I need to add anything else.
Don't hesitate to post if you find anything, it's a large and new extension for me so I'm sure there could be other items especially as Thunderbird is changing quickly.

a review be great  ;-)

**Comment by cleidigh** [comment] 2019-10-23 19:08
Fixed

**Closed** 2019-10-23 19:08 UTC
Labels: bug
