### ISSUE TITLE
import-export-tools-ng-10.0.0-b10-tb.xpi

### ISSUE THREAD

**Issue by suseuser188** [thundernest/import-export-tools-ng#148] opened 2020-09-11 20:02 UTC
The beta installed on my Opensuse distro Thunderbird with no problems. However, while it will export a folder's messages in html format correctly, the index.html file created is empty.

**Comment by cleidigh** [comment] 2020-09-11 22:32
@suseuser188 
I just checked b10 on my  mint vM 
that generated the index correctly.  can you check and post in the output in the error console?
also see what happens if you try to export EML with index .
Christopher

**Comment by suseuser188** [comment] 2020-09-11 22:44
First, here is the output in the error console: 
Uncaught ReferenceError: convertPRTimeToString is not defined
    createIndex chrome://mboximport/content/mboximport/exportTools.js:787
    IETrunExport chrome://mboximport/content/mboximport/exportTools.js:622
    exportAllMsgsDelayed chrome://mboximport/content/mboximport/exportTools.js:605
    exportAllMsgsStart chrome://mboximport/content/mboximport/exportTools.js:393

Secondly, exporting as EML with index has the same result: messages are correctly export, index file is empty.

**Comment by cleidigh** [comment] 2020-09-11 22:55
@suseuser188 
Excellent, but that is weird I just deprecated call.
thanks that helps a lot to solve the issue
I will probably post b11 this evening
Christopher

**Comment by cleidigh** [comment] 2020-09-11 23:02
@suseuser188 
I just reconfirmed what I suspected.  b10 has that function removed
somehow it prior version is cached
I would uninstall, restart, restart, install
Christopher

**Comment by suseuser188** [comment] 2020-09-12 10:16
Still no joy. Here are the contents of the error console:
Uncaught ReferenceError: convertPRTimeToString is not defined
    createIndex chrome://mboximport/content/mboximport/exportTools.js:787
    onAfterStopRequest chrome://mboximport/content/mboximport/exportTools.js:1532
    onStopRequest68 chrome://mboximport/content/mboximport/exportTools.js:1354
exportTools.js:787:5
Error opening input stream (invalid filename?): chrome://mboximport/content/composeOverlay.js implementation.js:505
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
Error opening input stream (invalid filename?): chrome://mboximport/content/composeOverlay.js implementation.js:505
window.controllers/Controllers is deprecated. Do not use it for UA detection. blank

**Comment by cleidigh** [comment] 2020-09-12 17:14
I did not understand but this is clearly from an old version.
Do the uninstall again then try restarting with a command line option
./thunderbird --purgecaches

**Comment by sfhowes** [comment] 2020-09-12 23:47
TB 78.2.2 32b/W10, removed b11, restarted with --purgecaches, installed b11.  Exporting all messages in a folder as just index (csv) produces empty folder, but just index (HTML) works for 2 of 3 IMAP Inbox folders; fails with outlook.com.

**Comment by cleidigh** [comment] 2020-09-13 01:44
@sfhowes 
Thanks!
I found several issues with b11 , b12 has several fixes for indexes.
I don't understand what you mean about failures with Outlook.com?
 look for b12 tomorrow/late tonight.

**Comment by sfhowes** [comment] 2020-09-13 01:50
> 
> 
> @sfhowes
> Thanks!
> I found several issues with b11 , b12 has several fixes for indexes.
> I don't understand what you mean about failures with Outlook.com?
> look for b12 tomorrow/late tonight.

It's a mystery to me.  Creating an html index worked for an AOL account and one from my ISP, but not the Hotmail Inbox or other standard folders.  It does work for a user-created folder on this account.  Will test b12.

**Comment by cleidigh** [comment] 2020-09-13 02:21
@sfhowes 
if I push a temporary b12 now can you test it?
Christopher

**Comment by sfhowes** [comment] 2020-09-13 02:28
Yes, waiting for b12.

**Comment by cleidigh** [comment] 2020-09-13 03:02
@sfhowes 
b12 posted
just re- verified CSV indexing under Windows/68
I've been testing on 78 all day, getting very close to Release

**Comment by sfhowes** [comment] 2020-09-13 03:34
With b12, html and csv indexes created for 2 of the 3 accounts and Local Folders, but not for newsgroups.  Hotmail account still fails on Inbox, Sent.  Works fine also on gmail Inbox.

**Comment by cleidigh** [comment] 2020-09-13 03:46
hmm
a bit strange, although I have no idea about handling the newsgroups, the Hotmail account must have something different
is it pop?
or the other way around?

**Comment by sfhowes** [comment] 2020-09-13 03:52
All accounts IMAP.  When exporting to an html index, this appears in the error console:

Uncaught TypeError: stripDisplayName(...)[0] is undefined
    getSubjectForHdr chrome://mboximport/content/mboximport/utils.js:166
    IETstoreHeaders chrome://mboximport/content/mboximport/exportTools.js:2004
    exportAllMsgsDelayed chrome://mboximport/content/mboximport/exportTools.js:593
    exportAllMsgsStart chrome://mboximport/content/mboximport/exportTools.js:392

**Comment by cleidigh** [comment] 2020-09-13 04:01
okay that helps
do you get that error for every account?

**Comment by sfhowes** [comment] 2020-09-13 04:04
The error only appears for the Hotmail account.

**Comment by cleidigh** [comment] 2020-09-13 04:06
this is an issue with headers
I will try to create something good for debugging output
not sure how far I can get tonight,6 close to bedtime

**Comment by cleidigh** [comment] 2020-09-13 04:20
this has output for every message
we should see the error for the exact message
in the output
[import-export-tools-ng-10.0.0-b12-1-tb.zip](https://github.com/thundernest/import-export-tools-ng/files/5213619/import-export-tools-ng-10.0.0-b12-1-tb.zip)

**Comment by cleidigh** [comment] 2020-09-13 04:21
then we can figure out the header problem
I have heard Hotmail has a bunch of issues

**Comment by sfhowes** [comment] 2020-09-13 04:44
The error console now includes something like this for every message:

strip off names Your product key utils.js:167:10
address is utils.js:123:11
{}
​
<prototype>: Object { … }
utils.js:124:11
Windows@e-mail.microsoft.com utils.js:170:10
address is utils.js:123:11
{}
​
<prototype>: Object { … }
utils.js:124:11
xxxxxxxx@hotmail.com

**Comment by cleidigh** [comment] 2020-09-13 04:49
exactly
at some point you should see the prior err 
at the e-mail that is the issue
then we can get the e-mail source and look at it
I have to sign off 
so I will look for your results tomorrow

**Comment by sfhowes** [comment] 2020-09-13 05:00
Yes, the previous error appeared after a message that made the export empty, but when I moved it to another folder, the csv and html exports were correct.  The offending message was sent from a gmail account with Apple Mail.

**Comment by suseuser188** [comment] 2020-09-13 11:29
Just to let you know. I decided to try one more time with b10. I uninstalled b10. Shutdown Thunderbird. Then I deleted the cache completely (rm -r).  Restarted Thunderbird and reinstalled b10. Presto, all is well, the program works as intended.

**Comment by cleidigh** [comment] 2020-09-13 18:13
@suseuser188 
That's great!  and I am going to have to investigate how if possible to avoid this.
Note avoid b11, b12 should be a first release candidate.
thanks again for going through the debugging effort, that sort of help it's really important
Christopher

**Comment by cleidigh** [comment] 2020-09-13 20:42
@sfhowes 
I will be off-line Shortly.
I wanted to throw a few more ideas out:
- try to Copy a few messages around the one you think is the issue
- if you think you have really found the one open the message and copy the source so we can see the flags
- export folder and reimport an see if the problem continues
Christopher

**Comment by sfhowes** [comment] 2020-09-13 22:57
I'm sure I've found the culprit, as removing it makes the index export work.  Exporting and re-importing has no effect.  Here is the source, absent the message body;

Received: from BN6PR06CA0019.namprd06.prod.outlook.com (10.175.123.157) by
 CO2PR0601MB0936.namprd06.prod.outlook.com (10.160.10.15) with Microsoft SMTP
 Server (version=TLS1_0, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P384) id
 15.1.619.10 via Mailbox Transport; Thu, 22 Sep 2016 03:51:32 +0000
Received: from inbound.mail.protection.outlook.com (216.32.180.184) by
 BN6PR06CA0019.outlook.office365.com (10.175.123.157) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
 15.1.609.9 via Frontend Transport; Thu, 22 Sep 2016 03:51:32 +0000
Received: from BN3NAM01FT062.eop-nam01.prod.protection.outlook.com
 (10.152.66.59) by BN3NAM01HT229.eop-nam01.prod.protection.outlook.com
 (10.152.66.220) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id 15.1.629.5; Thu, 22 Sep
 2016 03:51:31 +0000
Received: from COL004-MC6F3.hotmail.com (10.152.66.53) by
 BN3NAM01FT062.mail.protection.outlook.com (10.152.66.186) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
 15.1.629.5 via Frontend Transport; Thu, 22 Sep 2016 03:51:30 +0000
Received: from mail-io0-f169.google.com ([209.85.223.169]) by COL004-MC6F3.hotmail.com over TLS secured channel with Microsoft SMTPSVC(7.5.7601.23143);
	 Wed, 21 Sep 2016 20:51:30 -0700
Received: by mail-io0-f169.google.com with SMTP id m186so73541826ioa.2
        for <xxxxxx@hotmail.com>; Wed, 21 Sep 2016 20:51:30 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=from:content-transfer-encoding:date:subject:message-id:mime-version;
        bh=FcErcAAX68Kf93R5+umWWzdLeU9hOHpHxWpPwCxWThY=;
        b=H5Bl2dEE6Y3BNHjW+t/3MUlyl5diB7tkBjfJ6pJFp3H9USHSQvtBX9Wsx4DcKivjG1
         wfYNnPdhzWcsHj5J+kDkbj3qtC9Gd9XVaYKiPAy+6DE1G681gxgWP3kULvVT/T+ly3oJ
         PLNM3dfoA5dq4I+O9Au0POoLw5ZqrQO90dWEB1Umj80AhDiFXfOhhVbwRx92zpjOJm/2
         lgicwdlneU9UoM5I/z0s4REAhPVWAL0+ldLUOrqX6k8ydxgwN8brVzXnjQjwh1bTj2Wl
         DAfJ9BziEkgTk8HmsEkhf+YZDcqaAW44rTq/8ikS0t2o8CyzKigllrOOmnltjqwTWTcz
         AHSA==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:from:content-transfer-encoding:date:subject
         :message-id:mime-version;
        bh=FcErcAAX68Kf93R5+umWWzdLeU9hOHpHxWpPwCxWThY=;
        b=hmQD5lSnkABVY/1LGls8y0rjqzksdtlglrSNO9Bns5mP0AmVL2cEJESG7b9E53pY0k
         IAnw+SJZbzlwnCW0eyyBeSvyBkD9j880uiYsAbO7IcEp9uHy+kDYGODR1O3+dbt2ypU4
         mv7G1UbYyqDxXGn4bL6LARcjeteTcwtbwaQLoYufIYyYus3N44Fzy68aIrCPYaf4MyN0
         7WMJ4a8B69lBsZn3i2lJmC7Pn11kGWx4idXsI8kRLQr1xwzMbxlskPpcuUmrT4i2sCdu
         lSNG4cC79gupz0bApWn/Vnd8J+FqhvL07BQRB2zM9qMMVsoqq6W4fFWRAXYRDYwOq42v
         noeg==
X-Gm-Message-State: AE9vXwN3J99DYlgr1yvrBohs1buomuuTFVSo3IUtWAQAiJki8I0mPC7OXVN2WwUQ7RSdAw==
X-Received: by 10.107.3.67 with SMTP id 64mr326427iod.55.1474516290231;
        Wed, 21 Sep 2016 20:51:30 -0700 (PDT)
Return-Path: xxxxxxxx@gmail.com
Received: from [192.168.0.40] (S010684948cd37d43.wp.xxxxxxx.net. [24.77.139.138])
        by smtp.gmail.com with ESMTPSA id 27sm152188iok.3.2016.09.21.20.51.28
        (version=TLS1 cipher=ECDHE-RSA-AES128-SHA bits=128/128);
        Wed, 21 Sep 2016 20:51:29 -0700 (PDT)
From: XXXXXX <xxxxxxx@gmail.com>
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
Date: Wed, 21 Sep 2016 22:51:27 -0500
Subject: xxxxxxx
Message-Id: <9C3A4046-AC03-4319-91BD-BACE938299D5@gmail.com>
X-Mailer: Apple Mail (2.2104)
BCC:
X-OriginalArrivalTime: 22 Sep 2016 03:51:30.0548 (UTC) FILETIME=[9A616B40:01D21484]
X-MS-Exchange-Organization-Network-Message-Id: 96540c37-1617-42ab-1cf8-08d3e29bbd34
X-EOPAttributedMessage: 0
X-EOPTenantAttributedMessage: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa:0
X-MS-Exchange-Organization-MessageDirectionality: Incoming
CMM-sender-ip: 209.85.223.169
CMM-sending-ip: 209.85.223.169
CMM-Authentication-Results: hotmail.com; spf=pass (sender IP is
 209.85.223.169; identity alignment result is pass and alignment mode is
 relaxed) smtp.mailfrom=xxxxxxx@gmail.com; dkim=pass (identity alignment
 result is pass and alignment mode is relaxed) header.d=gmail.com; x-hmca=pass
 header.id=xxxxxxxx@gmail.com
CMM-X-SID-PRA: xxxxxxxx@gmail.com
CMM-X-AUTH-Result: PASS
CMM-X-SID-Result: PASS
CMM-X-Message-Status: n:n
CMM-X-Message-Delivery: Vj0xLjE7dXM9MDtsPTE7YT0xO0Q9MTtHRD0xO1NDTD0w
CMM-X-Message-Info: gamVN+8Ez8V+RHg+F+brAQZ8tAtOxSjdRSacJAdbEAWymCSdQTB6c2uKzGLhX1HWQyrc4Y7oTpIJUA58cWR8OlDt0d0y6/l1JAiaPB6FOF4XoCGKbAO7HXeCZalM2cJzSMucf7wrUOOmauX7me1KV+JRgpezJbjbDm9pAnS+wb5PdYrhmZA0tfRQHTMs3DzMCQZmaOV+cW4ijHqINfjaNYpzT9pgXjySaXSgc+7XmEpMAnEjqUkq1sn8lErHe0Bd
X-MS-Exchange-Organization-PCL: 2
X-Microsoft-Exchange-Diagnostics: 1;BN3NAM01FT062;1:/73sIOkPifvw76ah/wJR2ihv3QpUvjCHkDuxFCbN9A6bwXeopoZz36oV9aAPlmPfcbJRbOFGxEOGoSBv8DJkMGwgZ/q5sz2SvnArSDdKE6BhYcVx/io9AWIjMk3g6Nq2/1jG4Q3T0f4T8zXolA1vnQ==
X-Forefront-Antispam-Report: EFV:NLI;SFV:NSPM;SFS:(98900003);DIR:INB;SFP:;SCL:1;SRVR:BN3NAM01HT229;H:COL004-MC6F3.hotmail.com;FPR:;SPF:None;LANG:en;
X-MS-Office365-Filtering-Correlation-Id: 96540c37-1617-42ab-1cf8-08d3e29bbd34
X-Microsoft-Exchange-Diagnostics: 1;BN3NAM01HT229;2:Jj0GIuAVrYuCN0GzehT7XZONcIcCSJxWIWfFgWjjHPUdqi62ZVJO72Xn3i1Np4VIUwetlWXclZzxBxkHk37NGdUlVAnHP2xBU6Mvssg8CzpGir/+GIdzqglkLUzeK9P65VjI52x3LRVRnQNgIaIgt9TyaiCu7eBE4CYTxfxLRHEwi8mvJFaJYXOaLvq/6krL+jCB01Gwt38HnNM0s0RwPg==;3:GdDhtky8uwtwVl9Mw+lVlC3+GwSJeTTHcb+WxDJ1arXEkxpFU/4gxjbnvlLn9n2EX2cbBE4fe86LOw+H8uBx7vtrD/zSDfpuwvvbJ1lazJ11lfoYMDO023nOdGZIX2GPBUOlx0j2s9TkayjNcCK52ymyBoYBNWB7y79XfNmfhQI=;25:aeHYbW/3edDVVi1yEoUa1m6W+yM8guiSy3BpIja1QtalnTNh1tBnaijaiYVgE2i7bWkVPpX6x7PWhtDzP7WwA7m7AH4f7NUwZrrRJfGdlva5/r6jpQAWDYrQax5YuGV84dvngSuk4RghEY+svoks2ElYqgGEwecN0lOozl7zJ9BV94WkFRAfW9WWiH+RHcrdtvBRmUUdXkxs6o1O62ECyZOr3COXsaHaumxAgHzZebcQXzPn15ANad3Jl24KRJKLcfku8V56Q1AJo3WfX9hGjS1jmkTepo98VHl4MmMMHusfWP6e+VN48sSqtjzipPPZNLovEory8O8jMt34kiR50M6FzfjmSDunU1wjeKsbJ6TggaUz2OJ2kfAsk0P6AP7Zjuu01N15Yw0EQCqvfXxuXXrDSRJn+UHSBwJEdmmmuCoJR6t+YQFXpLynW6vka7ww
X-Microsoft-Antispam: BCL:0;PCL:0;RULEID:(8291501002);SRVR:BN3NAM01HT229;
X-Microsoft-Exchange-Diagnostics: 1;BN3NAM01HT229;31:tR0TFLoVNzGN60Rw9mXxi7HsXEaXx1UeG3UyXFWzq0KI3odyK0QOutNhO9WGyN3/rmMMftC39+WgGHs95BxvaxpILOlDan/cYbqU+cnftyJA7ZsvRgHgYhO5svhKO5h0DC549L1W0OOfY5XKzwxlmkz6vB7TVRcJPgEXvU01l1jJzYI71r0nhzVV3o70LwsvmiGzJleAyIBI9UXSDrAznw+5deftcGg763ZGHDjXJ/I=;4:wYxhsLsfbJgRuIFFYE5Ctu9jHOc4P9E8woNU+Cbh36hnjEoMSv2EGC+XoTu9arvhHWPkPme9UrEUOqP/Imp1K5swL15UtoN+92fDMQ/5W1c1PVufJQsg1T5I1qEhQIpuMyzoCQ/AasKnoIK8PU4fXT3zo3QLT3f3FqbgIX39zOuo8PY86fn7VUat+qA9ornMprjYFmf0WafDFw9w7LaIg5oxygRzzVvT+aBtJs3YeRvuyF75NC2r5RvUFz0IXRBW2vPRf3pYvDDd+SWy5knKYg==;23:ObwU3CWsM7BZD6iLu8rRyo6m4VVcupldds7b9s2UnfoziWyI/7HFQxCI0167p9rqVwIB5AP/NQyfuxi0Biha9KCpRAoA2bLxozqyHtIYKgWT7VtC6OAXcYoXK47d8KjpuOd9QSAdU3ZPli3m94kSU8aw69rsNgJE8FRI/m0nwwFMeRS8JuDMB/dpCpujLPmrLmlZEA4IIzY25lOnOIOCVA==
X-Exchange-Antispam-Report-CFA-Test: BCL:0;PCL:0;RULEID:(82015046);SRVR:BN3NAM01HT229;BCL:0;PCL:0;RULEID:;SRVR:BN3NAM01HT229;
X-MS-Exchange-Organization-SCL: 1
X-Microsoft-Exchange-Diagnostics: 1;BN3NAM01HT229;6:SmlXBOskwbCMIaMeziNBf8YQCnS9zoUroj4a2uaLcH0tRPzlFuSA/zf9gzeJQsFKJN1TCov0V3GHOonn0aHTd1BV1IvHD5Lh8sy8XWE+rn8QxypVBea8HsFlbbBUIg9GjQp3FkghbbZWXlwKakTwrTI/UPHfos1ZVaqX30G42QgQCoKyeGrY8M5X5lNHY4NcPzwvx8BcrqH1Sxc7NQolHIXst5zgR2hI7CxoH4xD23Dqd3Zja5RopjdGqmiJ9WqyVEuxrhTYcE2mWzQmEmGsPo0wRO6Yl2ouRLcGWcZMzIG2UOC4nnnzK5NihhbSXusZ;5:KDfd/w4WzfV0Vi72iXjCl2xj2gBY4/EzZY8CMH+thHWXi3+IC3j0Ev3Vcnxm7x1x2DfK+FKSjtlQTpTRH21KRQFcee/rc+5bhWtCUYCSvFMM2I8b2gC5bMSfiWvWpIIBAxSPL3aCov4nd6e6CLGlNQ==;24:9/6Vl0NZjvjRHOP5GxlohklulFcNvLzkFY+MfVSrydURN168uMBJ9YY/hhgYPjry83ms8avWyZhXXpJmEcvd2NMkNP0wGK+FA3sq3jNPyUE=;7:sG0e0VkWj70nbSw/i8suzF6wQWj/i+zCNdrpYpwYspfjYOo4PFHnDYb9pRHlsSAAWkvN/7taI3v6i/vv+OTuYRGQrYhsirzVKlnDeB+UZky6hE9oKabdj52eA0zzsppcmPdcaIeK4GpMF3EIdl1J4pi0DLuHLVAq1+eZEV3rQLh8Bg4VNOfFS0T706et8uOyXiJc5BH3zLk1FIQvdyJdlvDgmg5Sq5L2DW1TPa1gNj6Q80BdglKYJu2om3huCdemUbQDvj9ivOnltciqVkiPcW0fzi9ebiuOqXxS/UrvSPReF3zYnfNw8Y1t7EiO/hSPcXJ0mOyytghuOoxtPvmn2Q==
SpamDiagnosticOutput: 1:99
SpamDiagnosticMetadata: NSPM
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 22 Sep 2016 03:51:30.6957
 (UTC)
X-MS-Exchange-CrossTenant-Id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-Transport-CrossTenantHeadersStamped: BN3NAM01HT229
X-MS-Exchange-Organization-AuthSource:
 BN3NAM01FT062.eop-nam01.prod.protection.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-OriginatorOrg: outlook.com
X-MS-Exchange-Transport-EndToEndLatency: 00:00:01.5240965
X-Microsoft-Antispam-Mailbox-Delivery:
	abwl:1;rwl:0;ex:0;auth:1;dest:I;WIMS-SenderIP:209.85.223.169;WIMS-SPF:gmail%2ecom;WIMS-DKIM:gmail%2ecom;WIMS-822:xxxxxxxxx%40gmail%2ecom;WIMS-PRA:xxxxxxxxxxx%40gmail%2ecom;WIMS-AUTH:PASS;ENG:(102400050)(102408045);OFR:SenderInAddressBook;
MIME-Version: 1.0

**Comment by cleidigh** [comment] 2020-09-14 19:58
@sfhowes 
that's great, I will see if I can reconstruct it enough to reproduce the problem, I know where the issue is, I just don't know the exact trigger.
Christopher

**Comment by cleidigh** [comment] 2020-09-14 23:21
@sfhowes 
okay, got it.
no just to the above e-mail lacks these headers:
To:
envelope-to:

interestingly enough, RFC1322 that covers e-mail/headers indicates this is      actually valid
when I have the name parser for naming tokens it never contemplated the recipient
related headers to be empty
look for b12 tonight
Christopher

**Comment by cleidigh** [comment] 2020-09-15 00:29
@sfhowes 
 fixed and tested in 68/78
I was able to create an e-mail from your snippet very clearly show the problem '

b12 posted

**Comment by sfhowes** [comment] 2020-09-15 03:55
The latest b12 now exports complete csv and html index files when the headerless message is in the folder, although of course the To entry is blank for that message.

**Comment by cleidigh** [comment] 2020-09-15 18:09
@sfhowes 
excellent, we fixed it!  I have already thought about the entity entering the index. I can use the existing word 'none'
Which I think is appropriate

**Comment by cleidigh** [comment] 2020-09-15 23:48
@sfhowes 
no more blank entries , if there is no recipient to address , I use '(none)'
this will be in b13 tonight
Christopher

**Comment by cleidigh** [comment] 2020-09-16 19:17
@suseuser188 
@sfhowes 
did everyone get to see b13?
I think we are good, yes?
ready to close?

**Comment by sfhowes** [comment] 2020-09-16 19:35
I tested the index export with b13 and it works fine, although I haven't tested other features.

**Comment by cleidigh** [comment] 2020-09-16 19:44
@sfhowes 
that's great thanks!
right now other than some more testing I am just concerned about 1 user reporting EML import issues.
Christopher

**Comment by cleidigh** [comment] 2020-09-28 01:56
Closed with v10
@suseuser188 
@sfhowes 
Thanks!

**Closed** 2020-09-28 01:56 UTC
