### ISSUE TITLE
Export with HTML-index doesn't work

### ISSUE THREAD

**Issue by alurasg** [thundernest/import-export-tools-ng#22] opened 2019-09-30 14:26 UTC
The export of the messages (EML) without HTML-index works perfectly, and the 'HTML index only' option does also work, but if I select the EML export with HTML-index, nothing happens. As in, nothing. I tried both of the add-ons, both with and without NG.

**Comment by cleidigh** [comment] 2019-10-01 05:05
@alurasg 
Thanks I will try to reproduce tomorrow.

**Comment by cleidigh** [comment] 2019-10-02 02:06
@alurasg 
I think I know what's happening here.  I got a bit confused myself during testing.
There are some UI/functional inconsistencies that are part of the original code.  More explicitly:
- The multiple context menus have slightly different options which can cause confusion.
- The "Export all messages in folder/EML" creates an HTML index by default (short answer)
- The "Export all messages in folder/with HTML index/EML" option is only available in the
  message context menu or the Tools/ImportExportTools NG/...  menu option
- Both of these options operate on selected messages - and these will create an index
- If nothing is selected nothing is exported (maybe a warning is appropriate)
- If you have one or more messages selected and use either the message context/tools menu approach, the messages and index will be exported.

I also think we are both seen the same thing with Thunderbird 60 since nothing  changed in this respect.  If you can retest with the information above and let me know that would be great.
Assuming there is no real bug here, I think the answer is some UI tweaks to make things clearer.

Because I adopted this add-on, I do not have the history or awareness of many of these types of issues.  Some short user instructions would probably also help.

Please report back, thanks!
@cleidigh

**Comment by alurasg** [comment] 2019-10-08 08:29
@cleidigh
Dear Cleidigh, thank you so much for your clear explanation! As I followed your instructions, I now succeeded in making an EML export with HTML-index. Thanks again!

**Comment by cleidigh** [comment] 2019-10-08 19:46
@alurasg 
Great, glad you got it working!
A review on the add-on site would be great if it's not too much trouble ;-)

**Comment by alurasg** [comment] 2019-10-09 10:45
No problem, just did! Thanks again!

**Comment by cleidigh** [comment] 2019-10-10 05:24
thanks for the very kind review!
closing up

**Closed by cleidigh** 2019-10-10 05:24 UTC
