### ISSUE TITLE
After import the subsubfolders are not shown

### ISSUE THREAD

**Issue by TomFromBe** [thundernest/import-export-tools-ng#320] opened 2022-05-08 18:21 UTC
Hello,
I exported an IMAP folder, and imported under my local folders (to see it it works)
However:
- In explorer I see the complete structure is available after import. So the  (.    & .msf-) files AND (.sbd-)subdirectores.  -> see left side of printscreen -> so looks OK

- However, in Thunderbird, I **don't** see the sub-subfolders. Thunderbird seems only to see the .msf files, and  does not show the (also imported and present) sbd-subdirectories. -> See right side of the printscreen

What am I doing wrong?
![image](https://user-images.githubusercontent.com/105170315/167309653-6e214f6c-b46d-4e34-9558-99ca46c55e2d.png)

Ps: Using Thunderbird 91.9.0 32bit on windows 10, and ImportExportTools NG 10.0.2

**Comment by cleidigh** [comment] 2022-06-18 04:17
@TomFromBe 
I am playing catch up.
Have you tried v11.1, it has many fixes for 91
@cleidigh

**Comment by TomFromBe** [comment] 2022-06-18 13:18
I have v 11.1 (note that the 'details'/description  still
        sais 'version 10.0.2 : Maintenance Release - November 14, 2020')
        
        But I had found the the but (and workaround).
        Issue:  If a folder A has subfolders, but folder A itself
        contain NO mails, then the subfolders are not shown
        when restored.
      Workaround: So i just added one mail to each
        (empty) folder (that holds subfolders).
        
        Kind regards,
         Tom
        
        
        
          On Sat, Jun 18, 2022, 06:18
            Christopher Leidigh ***@***.***>
            wrote:
          
          
            @TomFromBe
              I am playing catch up.
              Have you tried v11.1, it has many fixes for 91
              @cleidigh
            —
              Reply to this email directly, view it on GitHub,
              or unsubscribe.
              You are receiving this because you were mentioned.Message
                ID: ***@***.***>

**Comment by ggbal** [comment] 2022-06-29 15:34
That is the workaround. But this should be a bug, right?  In this case, it can't import correctly from its own export. Either export should create an empty mbox file for each folder when there is no email in that folder itself. Or the import should handle this situation.

**Comment by cleidigh** [comment] 2022-06-29 21:34
@TomFromBe 
@ggbal 
I am trying to see if this can be addressed in the v12 I am just about to release.
I did several small tests with folders with subfolders, but with no messages in the parent. Exported then imported fine.
So i cannot reproduce this.
Have either of you tried this with a test folder?
One thing I noticed in the screenshots from @TomFromBe is that I do not see an empty mbox file for the Archives folder, this is why that does not show.  That should be created by the export as my tests do.
@cleidigh

**Comment by ggbal** [comment] 2022-06-30 02:50
I created test folders in Local Folders with one empty parent folder containing a folder that has one email. Export works correctly with the empty file for the parent folder. 

However, when I created the same folder structure in the Gmail account in Thunderbird (which uses IMAP), the export doesn't generate the empty mbox file for the parent folder. See the screenshots attached. 

I think you got the same result. 
<img width="407" alt="Screen Shot 2022-06-29 at 7 46 42 PM GMT-7" src="https://user-images.githubusercontent.com/19229418/176582311-89df869e-8aac-4f11-b8c3-091c1504f716.png">
<img width="949" alt="Screen Shot 2022-06-29 at 7 46 10 PM GMT-7" src="https://user-images.githubusercontent.com/19229418/176582313-135d2580-7a1e-44fa-8224-cf4c8f35d2ac.png">
<img width="975" alt="Screen Shot 2022-06-29 at 7 45 44 PM GMT-7" src="https://user-images.githubusercontent.com/19229418/176582318-3f5a34b3-ea6b-4040-b042-db06d58e2dae.png">

**Comment by cleidigh** [comment] 2022-07-01 04:16
@ggbal 
@TomFromBe 
I  have a fix I believe, if you guys can test that would be very helpful.
I am surprised and concerned as this is non trivial and not reported until now.
https://github.com/thundernest/import-export-tools-ng/blob/v12.0.0/xpi/import-export-tools-ng-12.0.0-b3-tb.xpi

Thanks!
@cleidigh

**Comment by ggbal** [comment] 2022-07-01 04:37
I did some tests. It created the empty mbox. But the one for the root folder has the wrong name. it includes the parent folder name in it. See the screenshot. 
<img width="398" alt="Screen Shot 2022-06-30 at 9 35 49 PM GMT-7" src="https://user-images.githubusercontent.com/19229418/176824315-eac50ffc-b5ce-4af0-a401-7e4c16db2023.png">

**Comment by cleidigh** [comment] 2022-07-01 16:32
@ggbal 
ok we are close.  I exported my Gmail archives folder and it was ok.
I am not totally clear on your screenshot, looks like TB, but there are folders with the.sbd in the name which should ony show up in a file view.
Can you clarify?  I will try more tests and maybe come up with a common structure to test.
@cleidigh

**Comment by ggbal** [comment] 2022-07-01 18:02
You are right, I am using Mac. For the screenshot, the top folder I exported from TB is TestBug. And I export to the disk under a folder called Test

**Comment by cleidigh** [comment] 2022-07-01 18:37
@ggbal 
here's the OS neutral version 
https://github.com/thundernest/import-export-tools-ng/blob/v12.0.0/xpi/import-export-tools-ng-12.0.0-b4-tb.xpi
Hopefully I am correct 
@cleidigh

**Comment by ggbal** [comment] 2022-07-01 19:31
Yes, it worked. Thanks for the quick turn aournd.

**Comment by cleidigh** [comment] 2022-07-01 19:45
@ggbal 
Thanks for your quick testing!
So TBs  IMAP directorys in the profile have different behaviors than the local folders.
Imap directorys do not have an empty mbox file for empty folders, only an msf file.  This issue cannot be too old, I think TB may have changed this.
So a little cleanup and I can release.
@cleidigh

**Comment by cleidigh** [comment] 2022-07-02 19:31
Closed with v12

**Closed by cleidigh** 2022-07-02 19:31 UTC
Labels: bug
